(function() {

  var terrToTGroup = {
    "ad":     "EUROPE",
    // "ae":     "United Arab Emirates",
    // "af":     "Afghanistan, Islamic State of",
    // "ag":     "Antigua and Barbuda",
    // "ai":     "Anguilla",
    "al":     "EUROPE",
    "am":     "EUROPE",
    // "an":     "Netherlands Antilles",
    // "ao":     "Angola",
    // "aq":     "Antarctica",
    // "ar":     "Argentina",
    // "arpa":   "Old style Arpanet",
    // "as":     "American Samoa",
    "at":     "EUROPE",
    "au":     "APAC",
    // "aw":     "Aruba",
    "az":     "EUROPE",
    "ba":     "EUROPE",
    // "bb":     "Barbados",
    // "bd":     "Bangladesh",
    "be":     "EUROPE",
    // "bf":     "Burkina Faso",
    "bg":     "EUROPE",
    // "bh":     "Bahrain",
    // "bi":     "Burundi",
    // "bj":     "Benin",
    // "bm":     "Bermuda",
    // "bn":     "Brunei Darussalam",
    // "bo":     "Bolivia",
    // "br":     "Brazil",
    // "bs":     "Bahamas",
    // "bt":     "Bhutan",
    // "bv":     "Bouvet Island",
    // "bw":     "Botswana",
    "by":     "EUROPE",
    // "bz":     "Belize",
    // "ca":     "Canada",
    // "cc":     "Cocos (Keeling) Islands",
    // "cf":     "Central African Republic",
    // "cd":     "Congo, The Democratic Republic of the",
    // "cg":     "Congo",
    "ch":     "EUROPE",
    // "ci":     "Ivory Coast (Cote D'Ivoire)",
    // "ck":     "Cook Islands",
    // "cl":     "Chile",
    // "cm":     "Cameroon",
    "cn":     "APAC",
    // "co":     "Colombia",
    // "com":    "Commercial",
    // "cr":     "Costa Rica",
    "cs":     "EUROPE",
    // "cu":     "Cuba",
    // "cv":     "Cape Verde",
    // "cx":     "Christmas Island",
    "cy":     "EUROPE",
    "cz":     "EUROPE",
    "de":     "EUROPE",
    // "dj":     "Djibouti",
    "dk":     "EUROPE",
    // "dm":     "Dominica",
    // "do":     "Dominican Republic",
    // "dz":     "Algeria",
    // "ec":     "Ecuador",
    // "edu":    "Educational",
    "ee":     "EUROPE",
    // "eg":     "Egypt",
    // "eh":     "Western Sahara",
    // "er":     "Eritrea",
    "es":     "EUROPE",
    // "et":     "Ethiopia",
    "fi":     "EUROPE",
    // "fj":     "Fiji",
    // "fk":     "Falkland Islands",
    // "fm":     "Micronesia",
    // "fo":     "Faroe Islands",
    "fr":     "EUROPE",
    "fx":     "EUROPE",
    // "ga":     "Gabon",
    "gb":     "EUROPE",
    // "gd":     "Grenada",
    "ge":     "EUROPE",
    // "gf":     "French Guyana",
    // "gh":     "Ghana",
    "gi":     "EUROPE",
    "gl":     "EUROPE",
    // "gm":     "Gambia",
    // "gn":     "Guinea",
    "gov":    "USA",
    // "gp":     "Guadeloupe (French)",
    // "gq":     "Equatorial Guinea",
    "gr":     "EUROPE",
    "gs":     "EUROPE",
    // "gt":     "Guatemala",
    // "gu":     "Guam (USA)",
    // "gw":     "Guinea Bissau",
    // "gy":     "Guyana",
    "hk":     "APAC",
    // "hm":     "Heard and McDonald Islands",
    // "hn":     "Honduras",
    "hr":     "EUROPE",
    // "ht":     "Haiti",
    "hu":     "EUROPE",
    "id":     "APAC",
    "ie":     "EUROPE",
    "il":     "EUROPE",
    "in":     "APAC",
    // "int":    "International",
    // "io":     "British Indian Ocean Territory",
    // "iq":     "Iraq",
    // "ir":     "Iran",
    "is":     "EUROPE",
    "it":     "EUROPE",
    // "jm":     "Jamaica",
    // "jo":     "Jordan",
    "jp":     "APAC",
    // "ke":     "Kenya",
    "kg":     "EUROPE",
    "kh":     "APAC",
    // "ki":     "Kiribati",
    // "km":     "Comoros",
    // "kn":     "Saint Kitts & Nevis Anguilla",
    "kp":     "APAC",
    "kr":     "APAC",
    // "kw":     "Kuwait",
    // "ky":     "Cayman Islands",
    "kz":     "EUROPE",
    "la":     "APAC",
    // "lb":     "Lebanon",
    // "lc":     "Saint Lucia",
    "li":     "EUROPE",
    // "lk":     "Sri Lanka",
    // "lr":     "Liberia",
    // "ls":     "Lesotho",
    "lt":     "EUROPE",
    "lu":     "EUROPE",
    "lv":     "EUROPE",
    // "ly":     "Libya",
    // "ma":     "Morocco",
    "mc":     "EUROPE",
    "md":     "EUROPE",
    // "mg":     "Madagascar",
    // "mh":     "Marshall Islands",
    "mil":    "USA",
    "mk":     "EUROPE",
    // "ml":     "Mali",
    // "mm":     "Myanmar",
    // "mn":     "Mongolia",
    // "mo":     "Macau",
    // "mp":     "Northern Mariana Islands",
    // "mq":     "Martinique (French)",
    // "mr":     "Mauritania",
    // "ms":     "Montserrat",
    // "mt":     "Malta",
    // "mu":     "Mauritius",
    // "mv":     "Maldives",
    // "mw":     "Malawi",
    // "mx":     "Mexico",
    // "my":     "Malaysia",
    // "mz":     "Mozambique",
    // "na":     "Namibia",
    // "nato":   "NATO (this was purged in 1996 - see hq.nato.int)",
    // "nc":     "New Caledonia (French)",
    // "ne":     "Niger",
    // "net":    "Network",
    // "nf":     "Norfolk Island",
    // "ng":     "Nigeria",
    // "ni":     "Nicaragua",
    "nl":     "EUROPE",
    "no":     "EUROPE",
    "np":     "APAC",
    // "nr":     "Nauru",
    // "nt":     "Neutral Zone",
    // "nu":     "Niue",
    "nz":     "APAC",
    // "om":     "Oman",
    // "org":    "Non-Profit Making Organisations (sic)",
    // "pa":     "Panama",
    // "pe":     "Peru",
    // "pf":     "Polynesia (French)",
    // "pg":     "Papua New Guinea",
    "ph":     "APAC",
    "pk":     "APAC",
    "pl":     "EUROPE",
    // "pm":     "Saint Pierre and Miquelon",
    // "pn":     "Pitcairn Island",
    // "pr":     "Puerto Rico",
    "pt":     "EUROPE",
    // "pw":     "Palau",
    // "py":     "Paraguay",
    // "qa":     "Qatar",
    // "re":     "Reunion (French)",
    "ro":     "EUROPE",
    "ru":     "Russian Federation",
    // "rw":     "Rwanda",
    // "sa":     "Saudi Arabia",
    // "sb":     "Solomon Islands",
    // "sc":     "Seychelles",
    // "sd":     "Sudan",
    "se":     "EUROPE",
    "sg":     "APAC",
    // "sh":     "Saint Helena",
    "si":     "EUROPE",
    // "sj":     "Svalbard and Jan Mayen Islands",
    "sk":     "EUROPE",
    // "sl":     "Sierra Leone",
    // "sm":     "EUROPE",
    // "sn":     "Senegal",
    // "so":     "Somalia",
    // "sr":     "Suriname",
    // "st":     "Saint Tome (Sao Tome) and Principe",
    "su":     "EUROPE",
    // "sv":     "El Salvador",
    // "sy":     "Syria",
    // "sz":     "Swaziland",
    // "tc":     "Turks and Caicos Islands",
    // "td":     "Chad",
    // "tf":     "French Southern Territories",
    // "tg":     "Togo",
    "th":     "APAC",
    // "tj":     "Tadjikistan",
    // "tk":     "Tokelau",
    // "tm":     "Turkmenistan",
    // "tn":     "Tunisia",
    // "to":     "Tonga",
    "tp":     "APAC",
    "tr":     "EUROPE",
    // "tt":     "Trinidad and Tobago",
    // "tv":     "Tuvalu",
    "tw":     "APAC",
    // "tz":     "Tanzania",
    "ua":     "EUROPE",
    // "ug":     "Uganda",
    "uk":     "EUROPE",
    "um":     "USA",
    "us":     "USA",
    // "uy":     "Uruguay",
    "uz":     "EUROPE",
    "va":     "EUROPE",
    // "vc":     "Saint Vincent & Grenadines",
    // "ve":     "Venezuela",
    // "vg":     "Virgin Islands (British)",
    // "vi":     "Virgin Islands (USA)",
    "vn":     "APAC",
    // "vu":     "Vanuatu",
    // "wf":     "Wallis and Futuna Islands",
    // "ws":     "Samoa",
    // "ye":     "Yemen",
    // "yt":     "Mayotte",
    "yu":     "EUROPE",
    // "za":     "South Africa",
    // "zm":     "Zambia",
    // "zr":     "Zaire",
    // "zw":     "Zimbabwe",
    // extra terms
    // "ap":     "African Regional Industrial Property Organization",
    "bx":     "EUROPE",
    "ef":     "EUROPE",
    "em":     "EUROPE",
    "ep":     "EUROPE",
    "ev":     "EUROPE"
    // "gc":     "Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)",
    // "ib":     "International Bureau of WIPO",
    // "oa":     "African Intellectual Property Organization",
    // "wo":     "World Intellectual Property Organization"
  };

  var terrToName = {
    "ad":     "Andorra, Principality of",
    "ae":     "United Arab Emirates",
    "af":     "Afghanistan, Islamic State of",
    "ag":     "Antigua and Barbuda",
    "ai":     "Anguilla",
    "al":     "Albania",
    "am":     "Armenia",
    "an":     "Netherlands Antilles",
    "ao":     "Angola",
    "aq":     "Antarctica",
    "ar":     "Argentina",
    "arpa":   "Old style Arpanet",
    "as":     "American Samoa",
    "at":     "Austria",
    "au":     "Australia",
    "aw":     "Aruba",
    "az":     "Azerbaidjan",
    "ba":     "Bosnia-Herzegovina",
    "bb":     "Barbados",
    "bd":     "Bangladesh",
    "be":     "Belgium",
    "bf":     "Burkina Faso",
    "bg":     "Bulgaria",
    "bh":     "Bahrain",
    "bi":     "Burundi",
    "bj":     "Benin",
    "bm":     "Bermuda",
    "bn":     "Brunei Darussalam",
    "bo":     "Bolivia",
    "br":     "Brazil",
    "bs":     "Bahamas",
    "bt":     "Bhutan",
    "bv":     "Bouvet Island",
    "bw":     "Botswana",
    "by":     "Belarus",
    "bz":     "Belize",
    "ca":     "Canada",
    "cc":     "Cocos (Keeling) Islands",
    "cf":     "Central African Republic",
    "cd":     "Congo, The Democratic Republic of the",
    "cg":     "Congo",
    "ch":     "Switzerland",
    "ci":     "Ivory Coast (Cote D'Ivoire)",
    "ck":     "Cook Islands",
    "cl":     "Chile",
    "cm":     "Cameroon",
    "cn":     "China",
    "co":     "Colombia",
    "com":    "Commercial",
    "cr":     "Costa Rica",
    "cs":     "Former Czechoslovakia",
    "cu":     "Cuba",
    "cv":     "Cape Verde",
    "cx":     "Christmas Island",
    "cy":     "Cyprus",
    "cz":     "Czech Republic",
    "de":     "Germany",
    "dj":     "Djibouti",
    "dk":     "Denmark",
    "dm":     "Dominica",
    "do":     "Dominican Republic",
    "dz":     "Algeria",
    "ec":     "Ecuador",
    "edu":    "Educational",
    "ee":     "Estonia",
    "eg":     "Egypt",
    "eh":     "Western Sahara",
    "er":     "Eritrea",
    "es":     "Spain",
    "et":     "Ethiopia",
    "fi":     "Finland",
    "fj":     "Fiji",
    "fk":     "Falkland Islands",
    "fm":     "Micronesia",
    "fo":     "Faroe Islands",
    "fr":     "France",
    "fx":     "France (European Territory)",
    "ga":     "Gabon",
    "gb":     "Great Britain",
    "gd":     "Grenada",
    "ge":     "Georgia",
    "gf":     "French Guyana",
    "gh":     "Ghana",
    "gi":     "Gibraltar",
    "gl":     "Greenland",
    "gm":     "Gambia",
    "gn":     "Guinea",
    "gov":    "USA Government",
    "gp":     "Guadeloupe (French)",
    "gq":     "Equatorial Guinea",
    "gr":     "Greece",
    "gs":     "S. Georgia & S. Sandwich Isls.",
    "gt":     "Guatemala",
    "gu":     "Guam (USA)",
    "gw":     "Guinea Bissau",
    "gy":     "Guyana",
    "hk":     "Hong Kong",
    "hm":     "Heard and McDonald Islands",
    "hn":     "Honduras",
    "hr":     "Croatia",
    "ht":     "Haiti",
    "hu":     "Hungary",
    "id":     "Indonesia",
    "ie":     "Ireland",
    "il":     "Israel",
    "in":     "India",
    "int":    "International",
    "io":     "British Indian Ocean Territory",
    "iq":     "Iraq",
    "ir":     "Iran",
    "is":     "Iceland",
    "it":     "Italy",
    "jm":     "Jamaica",
    "jo":     "Jordan",
    "jp":     "Japan",
    "ke":     "Kenya",
    "kg":     "Kyrgyz Republic (Kyrgyzstan)",
    "kh":     "Cambodia, Kingdom of",
    "ki":     "Kiribati",
    "km":     "Comoros",
    "kn":     "Saint Kitts & Nevis Anguilla",
    "kp":     "North Korea",
    "kr":     "South Korea",
    "kw":     "Kuwait",
    "ky":     "Cayman Islands",
    "kz":     "Kazakhstan",
    "la":     "Laos",
    "lb":     "Lebanon",
    "lc":     "Saint Lucia",
    "li":     "Liechtenstein",
    "lk":     "Sri Lanka",
    "lr":     "Liberia",
    "ls":     "Lesotho",
    "lt":     "Lithuania",
    "lu":     "Luxembourg",
    "lv":     "Latvia",
    "ly":     "Libya",
    "ma":     "Morocco",
    "mc":     "Monaco",
    "md":     "Moldavia",
    "mg":     "Madagascar",
    "mh":     "Marshall Islands",
    "mil":    "USA Military",
    "mk":     "Macedonia",
    "ml":     "Mali",
    "mm":     "Myanmar",
    "mn":     "Mongolia",
    "mo":     "Macau",
    "mp":     "Northern Mariana Islands",
    "mq":     "Martinique (French)",
    "mr":     "Mauritania",
    "ms":     "Montserrat",
    "mt":     "Malta",
    "mu":     "Mauritius",
    "mv":     "Maldives",
    "mw":     "Malawi",
    "mx":     "Mexico",
    "my":     "Malaysia",
    "mz":     "Mozambique",
    "na":     "Namibia",
    "nato":   "NATO (this was purged in 1996 - see hq.nato.int)",
    "nc":     "New Caledonia (French)",
    "ne":     "Niger",
    "net":    "Network",
    "nf":     "Norfolk Island",
    "ng":     "Nigeria",
    "ni":     "Nicaragua",
    "nl":     "Netherlands",
    "no":     "Norway",
    "np":     "Nepal",
    "nr":     "Nauru",
    "nt":     "Neutral Zone",
    "nu":     "Niue",
    "nz":     "New Zealand",
    "om":     "Oman",
    "org":    "Non-Profit Making Organisations (sic)",
    "pa":     "Panama",
    "pe":     "Peru",
    "pf":     "Polynesia (French)",
    "pg":     "Papua New Guinea",
    "ph":     "Philippines",
    "pk":     "Pakistan",
    "pl":     "Poland",
    "pm":     "Saint Pierre and Miquelon",
    "pn":     "Pitcairn Island",
    "pr":     "Puerto Rico",
    "pt":     "Portugal",
    "pw":     "Palau",
    "py":     "Paraguay",
    "qa":     "Qatar",
    "re":     "Reunion (French)",
    "ro":     "Romania",
    "ru":     "Russian Federation",
    "rw":     "Rwanda",
    "sa":     "Saudi Arabia",
    "sb":     "Solomon Islands",
    "sc":     "Seychelles",
    "sd":     "Sudan",
    "se":     "Sweden",
    "sg":     "Singapore",
    "sh":     "Saint Helena",
    "si":     "Slovenia",
    "sj":     "Svalbard and Jan Mayen Islands",
    "sk":     "Slovak Republic",
    "sl":     "Sierra Leone",
    "sm":     "San Marino",
    "sn":     "Senegal",
    "so":     "Somalia",
    "sr":     "Suriname",
    "st":     "Saint Tome (Sao Tome) and Principe",
    "su":     "Former USSR",
    "sv":     "El Salvador",
    "sy":     "Syria",
    "sz":     "Swaziland",
    "tc":     "Turks and Caicos Islands",
    "td":     "Chad",
    "tf":     "French Southern Territories",
    "tg":     "Togo",
    "th":     "Thailand",
    "tj":     "Tadjikistan",
    "tk":     "Tokelau",
    "tm":     "Turkmenistan",
    "tn":     "Tunisia",
    "to":     "Tonga",
    "tp":     "East Timor",
    "tr":     "Turkey",
    "tt":     "Trinidad and Tobago",
    "tv":     "Tuvalu",
    "tw":     "Taiwan",
    "tz":     "Tanzania",
    "ua":     "Ukraine",
    "ug":     "Uganda",
    "uk":     "United Kingdom",
    "um":     "USA Minor Outlying Islands",
    "us":     "United States",
    "uy":     "Uruguay",
    "uz":     "Uzbekistan",
    "va":     "Holy See (Vatican City State)",
    "vc":     "Saint Vincent & Grenadines",
    "ve":     "Venezuela",
    "vg":     "Virgin Islands (British)",
    "vi":     "Virgin Islands (USA)",
    "vn":     "Vietnam",
    "vu":     "Vanuatu",
    "wf":     "Wallis and Futuna Islands",
    "ws":     "Samoa",
    "ye":     "Yemen",
    "yt":     "Mayotte",
    "yu":     "Yugoslavia",
    "za":     "South Africa",
    "zm":     "Zambia",
    "zr":     "Zaire",
    "zw":     "Zimbabwe",
    // extra terms
    "ap":     "African Regional Industrial Property Organization",
    "bx":     "Benelux Trademarks and Design Offices",
    "ef":     "Union of Countries under the European Community Patent Convention",
    "em":     "European Trademark Office",
    "ep":     "European Patent Organization (Union of countries under the European Patent Convention)",
    "ev":     "Eurasian Patent Organization",
    "gc":     "Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)",
    "ib":     "International Bureau of WIPO",
    "oa":     "African Intellectual Property Organization",
    "wo":     "World Intellectual Property Organization"
  };

  var ipcToName = {
    "A01B": "SOIL WORKING IN AGRICULTURE OR FORESTRY; PARTS, DETAILS, OR ACCESSORIES OF AGRICULTURAL MACHINES OR IMPLEMENTS, IN GENERAL",
    "A01C": "PLANTING; SOWING; FERTILISING",
    "A01D": "HARVESTING; MOWING",
    "A01F": "THRESHING",
    "A01G": "HORTICULTURE; CULTIVATION OF VEGETABLES, FLOWERS, RICE, FRUIT, VINES, HOPS, OR SEAWEED; FORESTRY; WATERING",
    "A01H": "NEW PLANTS OR PROCESSES FOR OBTAINING THEM; PLANT REPRODUCTION BY TISSUE CULTURE TECHNIQUES",
    "A01J": "MANUFACTURE OF DAIRY PRODUCTS",
    "A01K": "ANIMAL HUSBANDRY; CARE OF BIRDS, FISHES, INSECTS; FISHING; REARING OR BREEDING ANIMALS, NOT OTHERWISE PROVIDED FOR; NEW BREEDS OF ANIMALS",
    "A01L": "SHOEING OF ANIMALS",
    "A01M": "CATCHING, TRAPPING OR SCARING OF ANIMALS",
    "A01N": "PRESERVATION OF BODIES OF HUMANS OR ANIMALS OR PLANTS OR PARTS THEREOF",
    "A01P": "BIOCIDAL, PEST REPELLANT, PEST ATTRACTANT OR PLANT GROWTH REGULATORY ACTIVITY OF CHEMICAL COMPOUNDS OR PREPARATIONS",
    "A21B": "BAKERS' OVENS; MACHINES OR EQUIPMENT FOR BAKING",
    "A21C": "MACHINES OR EQUIPMENT FOR MAKING OR PROCESSING DOUGHS; HANDLING BAKED ARTICLES MADE FROM DOUGH",
    "A21D": "TREATMENT, e.g. PRESERVATION, OF FLOUR OR DOUGH FOR BAKING, e.g. BY ADDITION OF MATERIALS; BAKING; BAKERY PRODUCTS; PRESERVATION THEREOF",
    "A22B": "SLAUGHTERING",
    "A22C": "PROCESSING MEAT, POULTRY, OR FISH",
    "A23B": "PRESERVING, e.g. BY CANNING, MEAT, FISH, EGGS, FRUIT, VEGETABLES, EDIBLE SEEDS; CHEMICAL RIPENING OF FRUIT OR VEGETABLES; THE PRESERVED, RIPENED, OR CANNED PRODUCTS",
    "A23C": "DAIRY PRODUCTS, e.g. MILK, BUTTER, CHEESE; MILK OR CHEESE SUBSTITUTES; MAKING THEREOF",
    "A23D": "EDIBLE OILS OR FATS, e.g. MARGARINES, SHORTENINGS, COOKING OILS",
    "A23F": "COFFEE; TEA; THEIR SUBSTITUTES; MANUFACTURE, PREPARATION, OR INFUSION THEREOF",
    "A23G": "COCOA; COCOA PRODUCTS, e.g. CHOCOLATE; SUBSTITUTES FOR COCOA OR COCOA PRODUCTS; CONFECTIONERY; CHEWING GUM; ICE-CREAM; PREPARATION THEREOF",
    "A23J": "PROTEIN COMPOSITIONS FOR FOODSTUFFS; WORKING-UP PROTEINS FOR FOODSTUFFS; PHOSPHATIDE COMPOSITIONS FOR FOODSTUFFS",
    "A23K": "FEEDING-STUFFS SPECIALLY ADAPTED FOR ANIMALS; METHODS SPECIALLY ADAPTED FOR PRODUCTION THEREOF",
    "A23L": "FOODS, FOODSTUFFS, OR NON-ALCOHOLIC BEVERAGES, NOT COVERED BY SUBCLASSES ; A21D;  OR A23B-A23J; THEIR PREPARATION OR TREATMENT, e.g. COOKING, MODIFICATION OF NUTRITIVE QUALITIES, PHYSICAL TREATMENT",
    "A23N": "MACHINES OR APPARATUS FOR TREATING HARVESTED FRUIT, VEGETABLES, OR FLOWER BULBS IN BULK, NOT OTHERWISE PROVIDED FOR; PEELING VEGETABLES OR FRUIT IN BULK; APPARATUS FOR PREPARING ANIMAL FEEDING-STUFFS",
    "A23P": "SHAPING OR WORKING OF FOODSTUFFS, NOT FULLY COVERED BY A SINGLE OTHER SUBCLASS",
    "A24B": "MANUFACTURE OR PREPARATION OF TOBACCO FOR SMOKING OR CHEWING; TOBACCO; SNUFF",
    "A24C": "MACHINES FOR MAKING CIGARS OR CIGARETTES",
    "A24D": "CIGARS; CIGARETTES; TOBACCO SMOKE FILTERS; MOUTHPIECES FOR CIGARS OR CIGARETTES; MANUFACTURE OF TOBACCO SMOKE FILTERS OR MOUTHPIECES",
    "A24F": "SMOKERS' REQUISITES; MATCH BOXES",
    "A41B": "SHIRTS; UNDERWEAR; BABY LINEN; HANDKERCHIEFS",
    "A41C": "CORSETS; BRASSIÈRES",
    "A41D": "OUTERWEAR; PROTECTIVE GARMENTS; ACCESSORIES",
    "A41F": "GARMENT FASTENINGS; SUSPENDERS",
    "A41G": "ARTIFICIAL FLOWERS; WIGS; MASKS; FEATHERS",
    "A41H": "APPLIANCES OR METHODS FOR MAKING CLOTHES, e.g. FOR DRESS-MAKING, FOR TAILORING, NOT OTHERWISE PROVIDED FOR",
    "A42B": "HATS; HEAD COVERINGS",
    "A42C": "MANUFACTURING OR TRIMMING HATS OR OTHER HEAD COVERINGS",
    "A43B": "CHARACTERISTIC FEATURES OF FOOTWEAR; PARTS OF FOOTWEAR",
    "A43C": "FASTENINGS OR ATTACHMENTS FOR FOOTWEAR; LACES IN GENERAL",
    "A43D": "MACHINES, TOOLS, EQUIPMENT OR METHODS FOR MANUFACTURING OR REPAIRING FOOTWEAR",
    "A44B": "BUTTONS, PINS, BUCKLES, SLIDE FASTENERS, OR THE LIKE",
    "A44C": "JEWELLERY; BRACELETS; OTHER PERSONAL ADORNMENTS; COINS",
    "A45B": "WALKING STICKS",
    "A45C": "PURSES; LUGGAGE; HAND CARRIED BAGS",
    "A45D": "HAIRDRESSING OR SHAVING EQUIPMENT; MANICURING OR OTHER COSMETIC TREATMENT",
    "A45F": "TRAVELLING OR CAMP EQUIPMENT; SACKS OR PACKS CARRIED ON THE BODY",
    "A46B": "BRUSHES",
    "A46D": "MANUFACTURE OF BRUSHES",
    "A47B": "TABLES; DESKS; OFFICE FURNITURE; CABINETS; DRAWERS; GENERAL DETAILS OF FURNITURE",
    "A47C": "CHAIRS",
    "A47D": "FURNITURE SPECIALLY ADAPTED FOR CHILDREN",
    "A47F": "SPECIAL FURNITURE, FITTINGS, OR ACCESSORIES FOR SHOPS, STOREHOUSES, BARS, RESTAURANTS, OR THE LIKE; PAYING COUNTERS",
    "A47G": "HOUSEHOLD OR TABLE EQUIPMENT",
    "A47H": "FURNISHINGS FOR WINDOWS OR DOORS",
    "A47J": "KITCHEN EQUIPMENT; COFFEE MILLS; SPICE MILLS; APPARATUS FOR MAKING BEVERAGES",
    "A47K": "SANITARY EQUIPMENT NOT OTHERWISE PROVIDED FOR",
    "A47L": "DOMESTIC WASHING OR CLEANING",
    "A61B": "DIAGNOSIS; SURGERY; IDENTIFICATION",
    "A61C": "DENTISTRY; APPARATUS OR METHODS FOR ORAL OR DENTAL HYGIENE",
    "A61D": "VETERINARY INSTRUMENTS, IMPLEMENTS, TOOLS, OR METHODS",
    "A61F": "FILTERS IMPLANTABLE INTO BLOOD VESSELS; PROSTHESES; DEVICES PROVIDING PATENCY TO, OR PREVENTING COLLAPSING OF, TUBULAR STRUCTURES OF THE BODY, E.G. STENTS; ORTHOPAEDIC, NURSING OR CONTRACEPTIVE DEVICES; FOMENTATION; TREATMENT OR PROTECTION OF EYES OR EARS; BANDAGES, DRESSINGS OR ABSORBENT PADS; FIRST-AID KITS",
    "A61G": "TRANSPORT, PERSONAL CONVEYANCES, OR ACCOMMODATION SPECIALLY ADAPTED FOR PATIENTS OR DISABLED PERSONS",
    "A61H": "PHYSICAL THERAPY APPARATUS, e.g. DEVICES FOR LOCATING OR STIMULATING REFLEX POINTS IN THE BODY; ARTIFICIAL RESPIRATION; MASSAGE; BATHING DEVICES FOR SPECIAL THERAPEUTIC OR HYGIENIC PURPOSES OR SPECIFIC PARTS OF THE BODY",
    "A61J": "CONTAINERS SPECIALLY ADAPTED FOR MEDICAL OR PHARMACEUTICAL PURPOSES; DEVICES OR METHODS SPECIALLY ADAPTED FOR BRINGING PHARMACEUTICAL PRODUCTS INTO PARTICULAR PHYSICAL OR ADMINISTERING FORMS; DEVICES FOR ADMINISTERING FOOD OR MEDICINES ORALLY; BABY COMFORTERS; DEVICES FOR RECEIVING SPITTLE",
    "A61K": "PREPARATIONS FOR MEDICAL, DENTAL, OR TOILET PURPOSES",
    "A61L": "METHODS OR APPARATUS FOR STERILISING MATERIALS OR OBJECTS IN GENERAL; DISINFECTION, STERILISATION, OR DEODORISATION OF AIR; CHEMICAL ASPECTS OF BANDAGES, DRESSINGS, ABSORBENT PADS, OR SURGICAL ARTICLES; MATERIALS FOR BANDAGES, DRESSINGS, ABSORBENT PADS, OR SURGICAL ARTICLES",
    "A61M": "DEVICES FOR INTRODUCING MEDIA INTO, OR ONTO, THE BODY ; DEVICES FOR PRODUCING OR ENDING SLEEP OR STUPOR",
    "A61N": "ELECTROTHERAPY; MAGNETOTHERAPY; RADIATION THERAPY; ULTRASOUND THERAPY",
    "A61P": "SPECIFIC THERAPEUTIC ACTIVITY OF CHEMICAL COMPOUNDS OR MEDICINAL PREPARATIONS",
    "A61Q": "SPECIFIC USE OF COSMETICS OR SIMILAR TOILET PREPARATIONS",
    "A62B": "DEVICES, APPARATUS OR METHODS FOR LIFE-SAVING",
    "A62C": "FIRE-FIGHTING",
    "A62D": "CHEMICAL MEANS FOR EXTINGUISHING FIRES; PROCESSES FOR MAKING HARMFUL CHEMICAL SUBSTANCES HARMLESS, OR LESS HARMFUL, BY EFFECTING A CHEMICAL CHANGE; COMPOSITION OF MATERIALS FOR COVERINGS OR CLOTHING FOR PROTECTING AGAINST HARMFUL CHEMICAL AGENTS; COMPOSITION OF MATERIALS FOR TRANSPARENT PARTS OF GAS-MASKS, RESPIRATORS, BREATHING BAGS OR HELMETS; COMPOSITION OF CHEMICAL MATERIALS FOR USE IN BREATHING APPARATUS",
    "A63B": "APPARATUS FOR PHYSICAL TRAINING, GYMNASTICS, SWIMMING, CLIMBING, OR FENCING; BALL GAMES; TRAINING EQUIPMENT",
    "A63C": "SKATES; SKIS; ROLLER SKATES; DESIGN OR LAYOUT OF COURTS, RINKS OR THE LIKE",
    "A63D": "BOWLING GAMES, e.g. SKITTLES, BOCCE OR BOWLS; INSTALLATIONS THEREFOR; BAGATELLE OR SIMILAR GAMES; BILLIARDS",
    "A63F": "CARD, BOARD, OR ROULETTE GAMES; INDOOR GAMES USING SMALL MOVING PLAYING BODIES; GAMES NOT OTHERWISE PROVIDED FOR",
    "A63G": "MERRY-GO-ROUNDS; SWINGS; ROCKING-HORSES ; CHUTES; SWITCHBACKS; SIMILAR DEVICES FOR PUBLIC AMUSEMENT",
    "A63H": "TOYS, e.g. TOPS, DOLLS, HOOPS, BUILDING BLOCKS",
    "A63J": "DEVICES FOR THEATRES, CIRCUSES, OR THE LIKE; CONJURING APPLIANCES OR THE LIKE",
    "A63K": "RACING; RIDING SPORTS; EQUIPMENT OR ACCESSORIES THEREFOR",
    "A99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "B01B": "BOILING; BOILING APPARATUS",
    "B01D": "SEPARATION",
    "B01F": "MIXING, e.g. DISSOLVING, EMULSIFYING, DISPERSING",
    "B01J": "CHEMICAL OR PHYSICAL PROCESSES, e.g. CATALYSIS, COLLOID CHEMISTRY; THEIR RELEVANT APPARATUS",
    "B01L": "CHEMICAL OR PHYSICAL LABORATORY APPARATUS FOR GENERAL USE ;",
    "B02B": "PREPARING GRAIN FOR MILLING; REFINING GRANULAR FRUIT TO COMMERCIAL PRODUCTS BY WORKING THE SURFACE",
    "B02C": "CRUSHING, PULVERISING, OR DISINTEGRATING IN GENERAL; MILLING GRAIN",
    "B03B": "SEPARATING SOLID MATERIALS USING LIQUIDS OR USING PNEUMATIC TABLES OR JIGS ;",
    "B03C": "MAGNETIC OR ELECTROSTATIC SEPARATION OF SOLID MATERIALS FROM SOLID MATERIALS OR FLUIDS; SEPARATION BY HIGH-VOLTAGE ELECTRIC FIELDS",
    "B03D": "FLOTATION; DIFFERENTIAL SEDIMENTATION",
    "B04B": "CENTRIFUGES",
    "B04C": "APPARATUS USING FREE VORTEX FLOW, e.g. CYCLONES",
    "B05B": "SPRAYING APPARATUS; ATOMISING APPARATUS; NOZZLES",
    "B05C": "APPARATUS FOR APPLYING LIQUIDS OR OTHER FLUENT MATERIALS TO SURFACES, IN GENERAL",
    "B05D": "PROCESSES FOR APPLYING LIQUIDS OR OTHER FLUENT MATERIALS TO SURFACES, IN GENERAL",
    "B06B": "GENERATING OR TRANSMITTING MECHANICAL VIBRATIONS IN GENERAL",
    "B07B": "SEPARATING SOLIDS FROM SOLIDS BY SIEVING, SCREENING, OR SIFTING OR BY USING GAS CURRENTS; OTHER SEPARATING BY DRY METHODS APPLICABLE TO BULK MATERIAL, e.g. LOOSE ARTICLES FIT TO BE HANDLED LIKE BULK MATERIAL",
    "B07C": "POSTAL SORTING; SORTING INDIVIDUAL ARTICLES, OR BULK MATERIAL FIT TO BE SORTED PIECE-MEAL, e.g. BY PICKING",
    "B08B": "CLEANING IN GENERAL; PREVENTION OF FOULING IN GENERAL",
    "B09B": "DISPOSAL OF SOLID WASTE",
    "B09C": "RECLAMATION OF CONTAMINATED SOIL",
    "B21B": "ROLLING OF METAL",
    "B21C": "MANUFACTURE OF METAL SHEETS, WIRE, RODS, TUBES, PROFILES OR LIKE SEMI-MANUFACTURED PRODUCTS OTHERWISE THAN BY ROLLING; AUXILIARY OPERATIONS USED IN CONNECTION WITH METAL-WORKING WITHOUT ESSENTIALLY REMOVING MATERIAL",
    "B21D": "WORKING OR PROCESSING OF SHEET METAL OR METAL TUBES, RODS OR PROFILES WITHOUT ESSENTIALLY REMOVING MATERIAL; PUNCHING",
    "B21F": "WORKING OR PROCESSING OF WIRE",
    "B21G": "MAKING NEEDLES, PINS, OR NAILS",
    "B21H": "MAKING PARTICULAR METAL OBJECTS BY ROLLING, e.g. SCREWS, WHEELS, RINGS, BARRELS, BALLS",
    "B21J": "FORGING; HAMMERING; PRESSING; RIVETING; FORGE FURNACES",
    "B21K": "MAKING FORGED OR PRESSED PRODUCTS, e.g. HORSE-SHOES, RIVETS, BOLTS, WHEELS",
    "B21L": "MAKING CHAINS",
    "B22C": "FOUNDRY MOULDING",
    "B22D": "CASTING OF METALS; CASTING OF OTHER SUBSTANCES BY THE SAME PROCESSES OR DEVICES",
    "B22F": "WORKING METALLIC POWDER; MANUFACTURE OF ARTICLES FROM METALLIC POWDER; MAKING METALLIC POWDER ; APPARATUS OR DEVICES SPECIALLY ADAPTED FOR METALLIC POWDER",
    "B23B": "TURNING; BORING",
    "B23C": "MILLING",
    "B23D": "PLANING; SLOTTING; SHEARING; BROACHING; SAWING; FILING; SCRAPING; LIKE OPERATIONS FOR WORKING METAL BY REMOVING MATERIAL, NOT OTHERWISE PROVIDED FOR",
    "B23F": "MAKING GEARS OR TOOTHED RACKS",
    "B23G": "THREAD CUTTING; WORKING OF SCREWS, BOLT HEADS, OR NUTS, IN CONJUNCTION THEREWITH",
    "B23H": "WORKING OF METAL BY THE ACTION OF A HIGH CONCENTRATION OF ELECTRIC CURRENT ON A WORKPIECE USING AN ELECTRODE WHICH TAKES THE PLACE OF A TOOL; SUCH WORKING COMBINED WITH OTHER FORMS OF WORKING OF METAL",
    "B23K": "SOLDERING OR UNSOLDERING; WELDING; CLADDING OR PLATING BY SOLDERING OR WELDING; CUTTING BY APPLYING HEAT LOCALLY, e.g. FLAME CUTTING; WORKING BY LASER BEAM",
    "B23P": "OTHER WORKING OF METAL; COMBINED OPERATIONS; UNIVERSAL MACHINE TOOLS",
    "B23Q": "DETAILS, COMPONENTS, OR ACCESSORIES FOR MACHINE TOOLS, e.g. ARRANGEMENTS FOR COPYING OR CONTROLLING ; MACHINE TOOLS IN GENERAL, CHARACTERISED BY THE CONSTRUCTION OF PARTICULAR DETAILS OR COMPONENTS; COMBINATIONS OR ASSOCIATIONS OF METAL-WORKING MACHINES, NOT DIRECTED TO A PARTICULAR RESULT",
    "B24B": "MACHINES, DEVICES, OR PROCESSES FOR GRINDING OR POLISHING ; DRESSING OR CONDITIONING OF ABRADING SURFACES; FEEDING OF GRINDING, POLISHING, OR LAPPING AGENTS",
    "B24C": "ABRASIVE OR RELATED BLASTING WITH PARTICULATE MATERIAL",
    "B24D": "TOOLS FOR GRINDING, BUFFING OR SHARPENING",
    "B25B": "TOOLS OR BENCH DEVICES NOT OTHERWISE PROVIDED FOR, FOR FASTENING, CONNECTING, DISENGAGING, OR HOLDING",
    "B25C": "HAND-HELD NAILING OR STAPLING TOOLS; MANUALLY-OPERATED PORTABLE STAPLING TOOLS",
    "B25D": "PERCUSSIVE TOOLS",
    "B25F": "COMBINATION OR MULTI-PURPOSE TOOLS NOT OTHERWISE PROVIDED FOR; DETAILS OR COMPONENTS OF PORTABLE POWER-DRIVEN TOOLS NOT PARTICULARLY RELATED TO THE OPERATIONS PERFORMED AND NOT OTHERWISE PROVIDED FOR",
    "B25G": "HANDLES FOR HAND IMPLEMENTS",
    "B25H": "WORKSHOP EQUIPMENT, e.g. FOR MARKING-OUT WORK; STORAGE MEANS FOR WORKSHOPS",
    "B25J": "MANIPULATORS; CHAMBERS PROVIDED WITH MANIPULATION DEVICES",
    "B26B": "HAND-HELD CUTTING TOOLS NOT OTHERWISE PROVIDED FOR",
    "B26D": "CUTTING; DETAILS COMMON TO MACHINES FOR PERFORATING, PUNCHING, CUTTING-OUT, STAMPING-OUT OR SEVERING",
    "B26F": "PERFORATING; PUNCHING; CUTTING-OUT; STAMPING-OUT; SEVERING BY MEANS OTHER THAN CUTTING",
    "B27B": "SAWS; COMPONENTS OR ACCESSORIES THEREFOR",
    "B27C": "PLANING, DRILLING, MILLING, TURNING, OR UNIVERSAL MACHINES",
    "B27D": "WORKING VENEER OR PLYWOOD",
    "B27F": "DOVETAILED WORK; TENONS; SLOTTING MACHINES; NAILING OR STAPLING MACHINES",
    "B27G": "ACCESSORY MACHINES OR APPARATUS FOR WORKING WOOD OR SIMILAR MATERIALS; TOOLS FOR WORKING WOOD OR SIMILAR MATERIALS ; SAFETY DEVICES FOR WOOD WORKING MACHINES OR TOOLS",
    "B27H": "BENDING; COOPERAGE; WHEEL-MAKING",
    "B27J": "MECHANICAL WORKING OF CANE, CORK, OR SIMILAR MATERIALS",
    "B27K": "PROCESSES, APPARATUS OR SELECTION OF SUBSTANCES FOR IMPREGNATING, STAINING, DYEING OR BLEACHING OF WOOD, OR FOR TREATING OF WOOD WITH PERMEANT LIQUIDS, NOT OTHERWISE PROVIDED FOR; CHEMICAL OR PHYSICAL TREATMENT OF CORK, CANE, REED, STRAW OR SIMILAR MATERIALS",
    "B27L": "REMOVING BARK OR VESTIGES OF BRANCHES ; SPLITTING WOOD; MANUFACTURE OF VENEER, WOODEN STICKS, WOOD SHAVINGS, WOOD FIBRES OR WOOD POWDER",
    "B27M": "WORKING OF WOOD NOT PROVIDED FOR IN SUBCLASSES ; B27B-B27L; MANUFACTURE OF SPECIFIC WOODEN ARTICLES",
    "B27N": "MANUFACTURE BY DRY PROCESSES OF ARTICLES, WITH OR WITHOUT ORGANIC BINDING AGENTS, MADE FROM PARTICLES OR FIBRES CONSISTING OF WOOD OR OTHER LIGNOCELLULOSIC OR LIKE ORGANIC MATERIAL",
    "B28B": "SHAPING CLAY OR OTHER CERAMIC COMPOSITIONS, SLAG OR MIXTURES CONTAINING CEMENTITIOUS MATERIAL, e.g. PLASTER ;",
    "B28C": "PREPARING CLAY; PRODUCING MIXTURES CONTAINING CLAY OR CEMENTITIOUS MATERIAL, e.g. PLASTER",
    "B28D": "WORKING STONE OR STONE-LIKE MATERIALS",
    "B29B": "PREPARATION OR PRETREATMENT OF THE MATERIAL TO BE SHAPED; MAKING GRANULES OR PREFORMS; RECOVERY OF PLASTICS OR OTHER CONSTITUENTS OF WASTE MATERIAL CONTAINING PLASTICS",
    "B29C": "SHAPING OR JOINING OF PLASTICS; SHAPING OF SUBSTANCES IN A PLASTIC STATE, IN GENERAL; AFTER- TREATMENT OF THE SHAPED PRODUCTS, e.g. REPAIRING",
    "B29D": "PRODUCING PARTICULAR ARTICLES FROM PLASTICS OR FROM SUBSTANCES IN A PLASTIC STATE",
    "B29K": "INDEXING SCHEME ASSOCIATED WITH SUBCLASSES B29B, B29C;  OR B29D, RELATING TO MOULDING MATERIALS OR TO MATERIALS FOR REINFORCEMENTS, FILLERS OR PREFORMED PARTS, e.g. INSERTS",
    "B29L": "INDEXING SCHEME ASSOCIATED WITH SUBCLASS B29C, RELATING TO PARTICULAR ARTICLES",
    "B30B": "PRESSES IN GENERAL; PRESSES NOT OTHERWISE PROVIDED FOR",
    "B31B": "MAKING BOXES, CARTONS, ENVELOPES, OR BAGS",
    "B31C": "MAKING WOUND ARTICLES, e.g. WOUND TUBES",
    "B31D": "MAKING OTHER PAPER ARTICLES",
    "B31F": "MECHANICAL WORKING OR DEFORMATION OF PAPER OR CARDBOARD",
    "B32B": "LAYERED PRODUCTS, i.e. PRODUCTS BUILT-UP OF STRATA OF FLAT OR NON-FLAT, e.g. CELLULAR OR HONEYCOMB, FORM",
    "B41B": "MACHINES OR ACCESSORIES FOR MAKING, SETTING, OR DISTRIBUTING TYPE; TYPE; PHOTOGRAPHIC OR PHOTOELECTRONIC COMPOSING DEVICES",
    "B41C": "PROCESSES FOR THE MANUFACTURE OR REPRODUCTION OF PRINTING SURFACES",
    "B41D": "APPARATUS FOR THE MECHANICAL REPRODUCTION OF PRINTING SURFACES FOR STEREOTYPE PRINTING; SHAPING ELASTIC OR DEFORMABLE MATERIAL TO FORM PRINTING SURFACES",
    "B41F": "PRINTING MACHINES OR PRESSES",
    "B41G": "APPARATUS FOR BRONZE PRINTING, LINE PRINTING, OR FOR BORDERING OR EDGING SHEETS OR LIKE ARTICLES; AUXILIARY APPARATUS FOR PERFORATING IN CONJUNCTION WITH PRINTING",
    "B41J": "TYPEWRITERS; SELECTIVE PRINTING MECHANISMS, i.e. MECHANISMS PRINTING OTHERWISE THAN FROM A FORME; CORRECTION OF TYPOGRAPHICAL ERRORS ;",
    "B41K": "STAMPS; STAMPING OR NUMBERING APPARATUS OR DEVICES",
    "B41L": "APPARATUS OR DEVICES FOR MANIFOLDING, DUPLICATING, OR PRINTING FOR OFFICE OR OTHER COMMERCIAL PURPOSES; ADDRESSING MACHINES OR LIKE SERIES-PRINTING MACHINES",
    "B41M": "PRINTING, DUPLICATING, MARKING, OR COPYING PROCESSES; COLOUR PRINTING",
    "B41N": "PRINTING PLATES OR FOILS ; MATERIALS FOR SURFACES USED IN PRINTING MACHINES FOR PRINTING, INKING, DAMPING, OR THE LIKE; PREPARING SUCH SURFACES FOR USE OR CONSERVING THEM",
    "B42B": "PERMANENTLY ATTACHING TOGETHER SHEETS, QUIRES, OR SIGNATURES, OR PERMANENTLY ATTACHING OBJECTS THERETO",
    "B42C": "BOOKBINDING",
    "B42D": "BOOKS; BOOK COVERS; LOOSE LEAVES; PRINTED MATTER OF SPECIAL FORMAT OR STYLE NOT OTHERWISE PROVIDED FOR; DEVICES FOR USE THEREWITH AND NOT OTHERWISE PROVIDED FOR; MOVABLE-STRIP WRITING OR READING APPARATUS",
    "B42F": "SHEETS TEMPORARILY ATTACHED TOGETHER; FILING APPLIANCES; FILE CARDS; INDEXING",
    "B43K": "IMPLEMENTS FOR WRITING OR DRAWING",
    "B43L": "ARTICLES FOR WRITING OR DRAWING UPON; ACCESSORIES FOR WRITING OR DRAWING",
    "B43M": "BUREAU ACCESSORIES NOT OTHERWISE PROVIDED FOR",
    "B44B": "MACHINES, APPARATUS OR TOOLS FOR ARTISTIC WORK, e.g. FOR SCULPTURING, GUILLOCHING, CARVING, BRANDING OR INLAYING",
    "B44C": "PRODUCING DECORATIVE EFFECTS ; PAPERHANGING",
    "B44D": "PAINTING OR ARTISTIC DRAWING, NOT OTHERWISE PROVIDED FOR; PRESERVING PAINTINGS; SURFACE TREATMENT TO OBTAIN SPECIAL ARTISTIC SURFACE EFFECTS OR FINISHES",
    "B44F": "SPECIAL DESIGNS OR PICTURES",
    "B60B": "VEHICLE WHEELS ; CASTORS; AXLES; INCREASING WHEEL ADHESION",
    "B60C": "VEHICLE TYRES",
    "B60D": "VEHICLE CONNECTIONS",
    "B60F": "VEHICLES FOR USE BOTH ON RAIL AND ON ROAD; VEHICLES CAPABLE OF TRAVELLING IN OR ON DIFFERENT MEDIA, e.g. AMPHIBIOUS VEHICLES",
    "B60G": "VEHICLE SUSPENSION ARRANGEMENTS",
    "B60H": "ARRANGEMENTS OR ADAPTATIONS OF HEATING, COOLING, VENTILATING, OR OTHER AIR-TREATING DEVICES SPECIALLY FOR PASSENGER OR GOODS SPACES OF VEHICLES",
    "B60J": "WINDOWS, WINDSCREENS, NON-FIXED ROOFS, DOORS, OR SIMILAR DEVICES FOR VEHICLES; REMOVABLE EXTERNAL PROTECTIVE COVERINGS SPECIALLY ADAPTED FOR VEHICLES",
    "B60K": "ARRANGEMENT OR MOUNTING OF PROPULSION UNITS OR OF TRANSMISSIONS IN VEHICLES; ARRANGEMENT OR MOUNTING OF PLURAL DIVERSE PRIME-MOVERS; AUXILIARY DRIVES; INSTRUMENTATION OR DASHBOARDS FOR VEHICLES; ARRANGEMENTS IN CONNECTION WITH COOLING, AIR INTAKE, GAS EXHAUST, OR FUEL SUPPLY, OF PROPULSION UNITS, IN VEHICLES",
    "B60L": "PROPULSION OF ELECTRICALLY-PROPELLED VEHICLES ; MAGNETIC SUSPENSION OR LEVITATION FOR VEHICLES; MONITORING OPERATING VARIABLES OF ELECTRICALLY-PROPELLED VEHICLES; ELECTRIC SAFETY DEVICES FOR ELECTRICALLY-PROPELLED VEHICLES",
    "B60M": "POWER SUPPLY LINES, OR DEVICES ALONG RAILS, FOR ELECTRICALLY-PROPELLED VEHICLES",
    "B60N": "VEHICLE PASSENGER ACCOMMODATION NOT OTHERWISE PROVIDED FOR",
    "B60P": "VEHICLES ADAPTED FOR LOAD TRANSPORTATION OR TO TRANSPORT, TO CARRY, OR TO COMPRISE SPECIAL LOADS OR OBJECTS",
    "B60Q": "ARRANGEMENT OF SIGNALLING OR LIGHTING DEVICES, THE MOUNTING OR SUPPORTING THEREOF OR CIRCUITS THEREFOR, FOR VEHICLES IN GENERAL",
    "B60R": "VEHICLES, VEHICLE FITTINGS, OR VEHICLE PARTS, NOT OTHERWISE PROVIDED FOR",
    "B60S": "SERVICING, CLEANING, REPAIRING, SUPPORTING, LIFTING, OR MANOEUVRING OF VEHICLES, NOT OTHERWISE PROVIDED FOR",
    "B60T": "VEHICLE BRAKE CONTROL SYSTEMS OR PARTS THEREOF; BRAKE CONTROL SYSTEMS OR PARTS THEREOF, IN GENERAL ; ARRANGEMENT OF BRAKING ELEMENTS ON VEHICLES IN GENERAL; PORTABLE DEVICES FOR PREVENTING UNWANTED MOVEMENT OF VEHICLES; VEHICLE MODIFICATIONS TO FACILITATE COOLING OF BRAKES",
    "B60V": "AIR-CUSHION VEHICLES",
    "B60W": "CONJOINT CONTROL OF VEHICLE SUB-UNITS OF DIFFERENT TYPE OR DIFFERENT FUNCTION; CONTROL SYSTEMS SPECIALLY ADAPTED FOR HYBRID VEHICLES; ROAD VEHICLE DRIVE CONTROL SYSTEMS FOR PURPOSES NOT RELATED TO THE CONTROL OF A PARTICULAR SUB-UNIT",
    "B61B": "RAILWAY SYSTEMS; EQUIPMENT THEREFOR NOT OTHERWISE PROVIDED FOR",
    "B61C": "LOCOMOTIVES; MOTOR RAILCARS",
    "B61D": "BODY DETAILS OR KINDS OF RAILWAY VEHICLES",
    "B61F": "RAIL VEHICLE SUSPENSIONS, e.g. UNDERFRAMES, BOGIES, ARRANGEMENTS OF WHEEL AXLES; RAIL VEHICLES FOR USE ON TRACKS OF DIFFERENT WIDTH; PREVENTING DERAILING; WHEELS GUARDS; OBSTRUCTION REMOVERS OR THE LIKE",
    "B61G": "COUPLINGS SPECIALLY ADAPTED FOR RAILWAY VEHICLES; DRAUGHT OR BUFFING APPLIANCES SPECIALLY ADAPTED FOR RAILWAY VEHICLES",
    "B61H": "BRAKES OR OTHER RETARDING APPARATUS PECULIAR TO RAIL VEHICLES; ARRANGEMENTS OR DIS-POSITIONS OF BRAKES OR OTHER RETARDING APPARATUS IN RAIL VEHICLES",
    "B61J": "SHIFTING OR SHUNTING OF RAIL VEHICLES",
    "B61K": "OTHER AUXILIARY EQUIPMENT FOR RAILWAYS",
    "B61L": "GUIDING RAILWAY TRAFFIC; ENSURING THE SAFETY OF RAILWAY TRAFFIC",
    "B62B": "HAND-PROPELLED VEHICLES, e.g. HAND CARTS OR PERAMBULATORS; SLEDGES",
    "B62C": "VEHICLES DRAWN BY ANIMALS",
    "B62D": "MOTOR VEHICLES; TRAILERS",
    "B62H": "CYCLE STANDS; SUPPORTS OR HOLDERS FOR PARKING OR STORING CYCLES; APPLIANCES PREVENTING OR INDICATING UNAUTHORISED USE OR THEFT OF CYCLES; LOCKS INTEGRAL WITH CYCLES; DEVICES FOR LEARNING TO RIDE CYCLES",
    "B62J": "CYCLE SADDLES OR SEATS; ACCESSORIES PECULIAR TO CYCLES AND NOT OTHERWISE PROVIDED FOR, e.g. ARTICLE CARRIERS OR CYCLE PROTECTORS",
    "B62K": "CYCLES; CYCLE FRAMES; CYCLE STEERING DEVICES; RIDER-OPERATED TERMINAL CONTROLS SPECIALLY ADAPTED FOR CYCLES; CYCLE AXLE SUSPENSIONS; CYCLE SIDECARS, FORECARS, OR THE LIKE",
    "B62L": "BRAKES SPECIALLY ADAPTED FOR CYCLES",
    "B62M": "RIDER PROPULSION OF WHEELED VEHICLES OR SLEDGES; POWERED PROPULSION OF SLEDGES OR CYCLES; TRANSMISSIONS SPECIALLY ADAPTED FOR SUCH VEHICLES",
    "B63B": "SHIPS OR OTHER WATERBORNE VESSELS; EQUIPMENT FOR SHIPPING",
    "B63C": "LAUNCHING, HAULING-OUT, OR DRY-DOCKING OF VESSELS; LIFE-SAVING IN WATER; EQUIPMENT FOR DWELLING OR WORKING UNDER WATER; MEANS FOR SALVAGING OR SEARCHING FOR UNDERWATER OBJECTS",
    "B63G": "OFFENSIVE OR DEFENSIVE ARRANGEMENTS ON VESSELS; MINE-LAYING; MINE-SWEEPING; SUBMARINES; AIRCRAFT CARRIERS",
    "B63H": "MARINE PROPULSION OR STEERING",
    "B63J": "AUXILIARIES ON VESSELS",
    "B64B": "LIGHTER-THAN-AIR AIRCRAFT",
    "B64C": "AEROPLANES; HELICOPTERS",
    "B64D": "EQUIPMENT FOR FITTING IN OR TO AIRCRAFT; FLYING SUITS; PARACHUTES; ARRANGEMENTS OR MOUNTING OF POWER PLANTS OR PROPULSION TRANSMISSIONS",
    "B64F": "GROUND OR AIRCRAFT-CARRIER-DECK INSTALLATIONS",
    "B64G": "COSMONAUTICS; VEHICLES OR EQUIPMENT THEREFOR",
    "B65B": "MACHINES, APPARATUS OR DEVICES FOR, OR METHODS OF, PACKAGING ARTICLES OR MATERIALS; UNPACKING ;",
    "B65C": "LABELLING OR TAGGING MACHINES, APPARATUS, OR PROCESSES",
    "B65D": "CONTAINERS FOR STORAGE OR TRANSPORT OF ARTICLES OR MATERIALS, e.g. BAGS, BARRELS, BOTTLES, BOXES, CANS, CARTONS, CRATES, DRUMS, JARS, TANKS, HOPPERS, FORWARDING CONTAINERS; ACCESSORIES, CLOSURES, OR FITTINGS THEREFOR; PACKAGING ELEMENTS; PACKAGES",
    "B65F": "GATHERING OR REMOVAL OF DOMESTIC OR LIKE REFUSE",
    "B65G": "TRANSPORT OR STORAGE DEVICES, e.g. CONVEYORS FOR LOADING OR TIPPING, SHOP CONVEYOR SYSTEMS OR PNEUMATIC TUBE CONVEYORS",
    "B65H": "HANDLING THIN OR FILAMENTARY MATERIAL, e.g. SHEETS, WEBS, CABLES",
    "B66B": "ELEVATORS; ESCALATORS OR MOVING WALKWAYS",
    "B66C": "CRANES; LOAD-ENGAGING ELEMENTS OR DEVICES FOR CRANES, CAPSTANS, WINCHES, OR TACKLES",
    "B66D": "CAPSTANS; WINCHES; TACKLES, e.g. PULLEY BLOCKS; HOISTS",
    "B66F": "HOISTING, LIFTING, HAULING, OR PUSHING, NOT OTHERWISE PROVIDED FOR, e.g. DEVICES WHICH APPLY A LIFTING OR PUSHING FORCE DIRECTLY TO THE SURFACE OF A LOAD",
    "B67B": "APPLYING CLOSURE MEMBERS TO BOTTLES, JARS, OR SIMILAR CONTAINERS; OPENING CLOSED CONTAINERS",
    "B67C": "FILLING WITH LIQUIDS OR SEMILIQUIDS, OR EMPTYING, OF BOTTLES, JARS, CANS, CASKS, BARRELS, OR SIMILAR CONTAINERS, NOT OTHERWISE PROVIDED FOR; FUNNELS",
    "B67D": "DISPENSING, DELIVERING, OR TRANSFERRING LIQUIDS, NOT OTHERWISE PROVIDED FOR",
    "B68B": "HARNESS; DEVICES USED IN CONNECTION THEREWITH; WHIPS OR THE LIKE",
    "B68C": "SADDLES; STIRRUPS",
    "B68F": "MAKING ARTICLES FROM LEATHER, CANVAS, OR THE LIKE",
    "B68G": "METHODS, EQUIPMENT, OR MACHINES FOR USE IN UPHOLSTERING; UPHOLSTERY NOT OTHERWISE PROVIDED FOR",
    "B81B": "MICRO-STRUCTURAL DEVICES OR SYSTEMS, e.g. MICRO-MECHANICAL DEVICES",
    "B81C": "PROCESSES OR APPARATUS SPECIALLY ADAPTED FOR THE MANUFACTURE OR TREATMENT OF MICRO-STRUCTURAL DEVICES OR SYSTEMS",
    "B82B": "NANO-STRUCTURES FORMED BY MANIPULATION OF INDIVIDUAL ATOMS, MOLECULES, OR LIMITED COLLECTIONS OF ATOMS OR MOLECULES AS DISCRETE UNITS; MANUFACTURE OR TREATMENT THEREOF",
    "B82Y": "SPECIFIC USES OR APPLICATIONS OF NANO-STRUCTURES; MEASUREMENT OR ANALYSIS OF NANO-STRUCTURES; MANUFACTURE  OR TREATMENT OF NANO-STRUCTURES",
    "B99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "C01B": "NON-METALLIC ELEMENTS; COMPOUNDS THEREOF",
    "C01C": "AMMONIA; CYANOGEN; COMPOUNDS THEREOF",
    "C01D": "COMPOUNDS OF ALKALI METALS, i.e. LITHIUM, SODIUM, POTASSIUM, RUBIDIUM, CAESIUM, OR FRANCIUM",
    "C01F": "COMPOUNDS OF THE METALS BERYLLIUM, MAGNESIUM, ALUMINIUM, CALCIUM, STRONTIUM, BARIUM, RADIUM, THORIUM, OR OF THE RARE-EARTH METALS",
    "C01G": "COMPOUNDS CONTAINING METALS NOT COVERED BY SUBCLASSES  C01D;  OR C01F;",
    "C02F": "TREATMENT OF WATER, WASTE WATER, SEWAGE, OR SLUDGE",
    "C03B": "MANUFACTURE OR SHAPING OF GLASS, OR OF MINERAL OR SLAG WOOL; SUPPLEMENTARY PROCESSES IN THE MANUFACTURE OR SHAPING OF GLASS, OR OF MINERAL OR SLAG WOOL",
    "C03C": "CHEMICAL COMPOSITION OF GLASSES, GLAZES, OR VITREOUS ENAMELS; SURFACE TREATMENT OF GLASS; SURFACE TREATMENT OF FIBRES OR FILAMENTS FROM GLASS, MINERALS OR SLAGS; JOINING GLASS TO GLASS OR OTHER MATERIALS",
    "C04B": "LIME; MAGNESIA; SLAG; CEMENTS; COMPOSITIONS THEREOF, e.g. MORTARS, CONCRETE OR LIKE BUILDING MATERIALS; ARTIFICIAL STONE; CERAMICS ; TREATMENT OF NATURAL STONE",
    "C05B": "PHOSPHATIC FERTILISERS",
    "C05C": "NITROGENOUS FERTILISERS",
    "C05D": "INORGANIC FERTILISERS NOT COVERED BY SUBCLASSES ; C05B, C05C; FERTILISERS PRODUCING CARBON DIOXIDE",
    "C05F": "ORGANIC FERTILISERS NOT COVERED BY SUBCLASSES ; C05B, C05C, e.g. FERTILISERS FROM WASTE OR REFUSE",
    "C05G": "MIXTURES OF FERTILISERS COVERED INDIVIDUALLY BY DIFFERENT SUBCLASSES OF CLASS ; C05; MIXTURES OF ONE OR MORE FERTILISERS WITH MATERIALS NOT HAVING A SPECIFIC FERTILISING ACTIVITY, e.g. PESTICIDES, SOIL-CONDITIONERS, WETTING AGENTS ; FERTILISERS CHARACTERISED BY THEIR FORM",
    "C06B": "EXPLOSIVE OR THERMIC COMPOSITIONS ; MANUFACTURE THEREOF; USE OF SINGLE SUBSTANCES AS EXPLOSIVES",
    "C06C": "DETONATING OR PRIMING DEVICES; FUSES; CHEMICAL LIGHTERS; PYROPHORIC COMPOSITIONS",
    "C06D": "MEANS FOR GENERATING SMOKE OR MIST; GAS-ATTACK COMPOSITIONS; GENERATION OF GAS FOR BLASTING OR PROPULSION",
    "C06F": "MATCHES; MANUFACTURE OF MATCHES",
    "C07B": "GENERAL METHODS OF ORGANIC CHEMISTRY; APPARATUS THEREFOR",
    "C07C": "ACYCLIC OR CARBOCYCLIC COMPOUNDS",
    "C07D": "HETEROCYCLIC COMPOUNDS",
    "C07F": "ACYCLIC, CARBOCYCLIC, OR HETEROCYCLIC COMPOUNDS CONTAINING ELEMENTS OTHER THAN CARBON, HYDROGEN, HALOGEN, OXYGEN, NITROGEN, SULFUR, SELENIUM OR TELLURIUM",
    "C07G": "COMPOUNDS OF UNKNOWN CONSTITUTION",
    "C07H": "SUGARS; DERIVATIVES THEREOF; NUCLEOSIDES; NUCLEOTIDES; NUCLEIC ACIDS",
    "C07J": "STEROIDS",
    "C07K": "PEPTIDES",
    "C08B": "POLYSACCHARIDES; DERIVATIVES THEREOF",
    "C08C": "TREATMENT OR CHEMICAL MODIFICATION OF RUBBERS",
    "C08F": "MACROMOLECULAR COMPOUNDS OBTAINED BY REACTIONS ONLY INVOLVING CARBON-TO-CARBON UNSATURATED BONDS",
    "C08G": "MACROMOLECULAR COMPOUNDS OBTAINED OTHERWISE THAN BY REACTIONS ONLY INVOLVING CARBON-TO-CARBON UNSATURATED BONDS",
    "C08H": "DERIVATIVES OF NATURAL MACROMOLECULAR COMPOUNDS",
    "C08J": "WORKING-UP; GENERAL PROCESSES OF COMPOUNDING; AFTER-TREATMENT NOT COVERED BY SUBCLASSES  C08B, C08C, C08F, C08G;  or C08H;",
    "C08K": "USE OF INORGANIC OR NON-MACROMOLECULAR ORGANIC SUBSTANCES AS COMPOUNDING INGREDIENTS",
    "C08L": "COMPOSITIONS OF MACROMOLECULAR COMPOUNDS",
    "C09B": "ORGANIC DYES OR CLOSELY-RELATED COMPOUNDS FOR PRODUCING DYES; MORDANTS; LAKES",
    "C09C": "TREATMENT OF INORGANIC MATERIALS, OTHER THAN FIBROUS FILLERS, TO ENHANCE THEIR PIGMENTING OR FILLING PROPERTIES ; PREPARATION OF CARBON BLACK",
    "C09D": "COATING COMPOSITIONS, e.g. PAINTS, VARNISHES OR LACQUERS; FILLING PASTES; CHEMICAL PAINT OR INK REMOVERS; INKS; CORRECTING FLUIDS; WOODSTAINS; PASTES OR SOLIDS FOR COLOURING OR PRINTING; USE OF MATERIALS THEREFOR",
    "C09F": "NATURAL RESINS; FRENCH POLISH; DRYING-OILS; DRIERS ; TURPENTINE",
    "C09G": "POLISHING COMPOSITIONS OTHER THAN FRENCH POLISH; SKI WAXES",
    "C09H": "PREPARATION OF GLUE OR GELATINE",
    "C09J": "ADHESIVES; NON-MECHANICAL ASPECTS OF ADHESIVE PROCESSES IN GENERAL; ADHESIVE PROCESSES NOT PROVIDED FOR ELSEWHERE; USE OF MATERIALS AS ADHESIVES",
    "C09K": "MATERIALS FOR APPLICATIONS NOT OTHERWISE PROVIDED FOR; APPLICATIONS OF MATERIALS NOT OTHERWISE PROVIDED FOR",
    "C10B": "DESTRUCTIVE DISTILLATION OF CARBONACEOUS MATERIALS FOR PRODUCTION OF GAS, COKE, TAR, OR SIMILAR MATERIALS",
    "C10C": "WORKING-UP TAR, PITCH, ASPHALT, BITUMEN; PYROLIGNEOUS ACID",
    "C10F": "DRYING OR WORKING-UP OF PEAT",
    "C10G": "CRACKING HYDROCARBON OILS; PRODUCTION OF LIQUID HYDROCARBON MIXTURES, e.g. BY DESTRUCTIVE HYDROGENATION, OLIGOMERISATION, POLYMERISATION ; RECOVERY OF HYDROCARBON OILS FROM OIL-SHALE, OIL-SAND, OR GASES; REFINING MIXTURES MAINLY CONSISTING OF HYDROCARBONS; REFORMING OF NAPHTHA; MINERAL WAXES",
    "C10H": "PRODUCTION OF ACETYLENE BY WET METHODS",
    "C10J": "PRODUCTION OF GASES CONTAINING CARBON MONOXIDE AND HYDROGEN FROM SOLID CARBONACEOUS MATERIALS BY PARTIAL OXIDATION PROCESSES INVOLVING OXYGEN OR STEAM  ; CARBURETTING AIR OR OTHER GASES",
    "C10K": "PURIFYING OR MODIFYING THE CHEMICAL COMPOSITION OF COMBUSTIBLE GASES CONTAINING CARBON MONOXIDE",
    "C10L": "FUELS NOT OTHERWISE PROVIDED FOR; NATURAL GAS; SYNTHETIC NATURAL GAS OBTAINED BY PROCESSES NOT COVERED BY SUBCLASSES ; C10G; OR C10K; LIQUEFIED PETROLEUM GAS;  USE OF ADDITIVES TO FUELS OR FIRES; FIRE-LIGHTERS",
    "C10M": "LUBRICATING COMPOSITIONS",
    "C10N": "INDEXING SCHEME ASSOCIATED WITH SUBCLASS C10M",
    "C11B": "PRODUCING, e.g. BY PRESSING RAW MATERIALS OR BY EXTRACTION FROM WASTE MATERIALS, REFINING OR PRESERVING FATS, FATTY SUBSTANCES, e.g. LANOLIN, FATTY OILS OR WAXES; ESSENTIAL OILS; PERFUMES",
    "C11C": "FATTY ACIDS FROM FATS, OILS OR WAXES; CANDLES; FATS, OILS OR FATTY ACIDS BY CHEMICAL MODIFICATION OF FATS, OILS, OR FATTY ACIDS OBTAINED THEREFROM",
    "C11D": "DETERGENT COMPOSITIONS; USE OF SINGLE SUBSTANCES AS DETERGENTS; SOAP OR SOAP-MAKING; RESIN SOAPS; RECOVERY OF GLYCEROL",
    "C12C": "BREWING OF BEER",
    "C12F": "RECOVERY OF BY-PRODUCTS OF FERMENTED SOLUTIONS; DENATURING OF, OR DENATURED, ALCOHOL",
    "C12G": "WINE; OTHER ALCOHOLIC BEVERAGES; PREPARATION THEREOF",
    "C12H": "PASTEURISATION, STERILISATION, PRESERVATION, PURIFICATION, CLARIFICATION, AGEING OF ALCOHOLIC BEVERAGES OR REMOVAL OF ALCOHOL THEREFROM",
    "C12J": "VINEGAR; ITS PREPARATION",
    "C12L": "PITCHING OR DEPITCHING MACHINES; CELLAR TOOLS",
    "C12M": "APPARATUS FOR ENZYMOLOGY OR MICROBIOLOGY",
    "C12N": "MICRO-ORGANISMS OR ENZYMES; COMPOSITIONS THEREOF",
    "C12P": "FERMENTATION OR ENZYME-USING PROCESSES TO SYNTHESISE A DESIRED CHEMICAL COMPOUND OR COMPOSITION OR TO SEPARATE OPTICAL ISOMERS FROM A RACEMIC MIXTURE",
    "C12Q": "MEASURING OR TESTING PROCESSES INVOLVING ENZYMES OR MICRO-ORGANISMS ; COMPOSITIONS OR TEST PAPERS THEREFOR; PROCESSES OF PREPARING SUCH COMPOSITIONS; CONDITION-RESPONSIVE CONTROL IN MICROBIOLOGICAL OR ENZYMOLOGICAL PROCESSES",
    "C12R": "INDEXING SCHEME ASSOCIATED WITH SUBCLASSES C12C-C12Q, RELATING TO MICRO-ORGANISMS",
    "C13B": "PRODUCTION OF SUCROSE; APPARATUS SPECIALLY ADAPTED THEREFOR",
    "C13K": "SACCHARIDES, OTHER THAN SUCROSE, OBTAINED FROM NATURAL SOURCES OR BY HYDROLYSIS OF NATURALLY OCCURRING DI-, OLIGO- OR POLYSACCHARIDES",
    "C14B": "MECHANICAL TREATMENT OR PROCESSING OF SKINS, HIDES, OR LEATHER IN GENERAL; PELT-SHEARING MACHINES; INTESTINE-SPLITTING MACHINES",
    "C14C": "TREATING SKINS, HIDES OR LEATHER WITH CHEMICALS, ENZYMES OR MICRO-ORGANISMS, e.g. TANNING, IMPREGNATING OR FINISHING; APPARATUS THEREFOR; COMPOSITIONS FOR TANNING",
    "C21B": "MANUFACTURE OF IRON OR STEEL",
    "C21C": "PROCESSING OF PIG-IRON, e.g. REFINING, MANUFACTURE OF WROUGHT-IRON OR STEEL ; TREATMENT IN MOLTEN STATE OF FERROUS ALLOYS",
    "C21D": "MODIFYING THE PHYSICAL STRUCTURE OF FERROUS METALS; GENERAL DEVICES FOR HEAT TREATMENT OF FERROUS OR NON-FERROUS METALS OR ALLOYS; MAKING METAL MALLEABLE BY DECARBURISATION, TEMPERING, OR OTHER TREATMENTS",
    "C22B": "PRODUCTION OR REFINING OF METALS ; PRETREATMENT OF RAW MATERIALS",
    "C22C": "ALLOYS",
    "C22F": "CHANGING THE PHYSICAL STRUCTURE OF NON-FERROUS METALS OR NON-FERROUS ALLOYS",
    "C23C": "COATING METALLIC MATERIAL; COATING MATERIAL WITH METALLIC MATERIAL; SURFACE TREATMENT OF METALLIC MATERIAL BY DIFFUSION INTO THE SURFACE, BY CHEMICAL CONVERSION OR SUBSTITUTION; COATING BY VACUUM EVAPORATION, BY SPUTTERING, BY ION IMPLANTATION OR BY CHEMICAL VAPOUR DEPOSITION, IN GENERAL",
    "C23D": "ENAMELLING OF, OR APPLYING A VITREOUS LAYER TO, METALS",
    "C23F": "NON-MECHANICAL REMOVAL OF METALLIC MATERIAL FROM SURFACES ; MULTI-STEP PROCESSES FOR SURFACE TREATMENT OF METALLIC MATERIAL INVOLVING AT LEAST ONE PROCESS PROVIDED FOR IN CLASS ; C23;  AND AT LEAST ONE PROCESS COVERED BY SUBCLASS C21D;  OR C22F;  OR CLASS C25",
    "C23G": "CLEANING OR DE-GREASING OF METALLIC MATERIAL BY CHEMICAL METHODS OTHER THAN ELECTROLYSIS",
    "C25B": "ELECTROLYTIC OR ELECTROPHORETIC PROCESSES FOR THE PRODUCTION OF COMPOUNDS OR NON- METALS; APPARATUS THEREFOR",
    "C25C": "PROCESSES FOR THE ELECTROLYTIC PRODUCTION, RECOVERY OR REFINING OF METALS; APPARATUS THEREFOR",
    "C25D": "PROCESSES FOR THE ELECTROLYTIC OR ELECTROPHORETIC PRODUCTION OF COATINGS; ELECTROFORMING",
    "C25F": "PROCESSES FOR THE ELECTROLYTIC REMOVAL OF MATERIALS FROM OBJECTS; APPARATUS THEREFOR",
    "C30B": "SINGLE-CRYSTAL GROWTH ; APPARATUS THEREFOR",
    "C40B": "COMBINATORIAL CHEMISTRY; LIBRARIES, e.g. CHEMICAL LIBRARIES, ; IN SILICO LIBRARIES",
    "C99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "D01B": "MECHANICAL TREATMENT OF NATURAL FIBROUS OR FILAMENTARY MATERIAL TO OBTAIN FIBRES OR FILAMENTS, e.g. FOR SPINNING",
    "D01C": "CHEMICAL OR BIOLOGICAL TREATMENT OF NATURAL FILAMENTARY OR FIBROUS MATERIAL TO OBTAIN FILAMENTS OR FIBRES FOR SPINNING; CARBONISING RAGS TO RECOVER ANIMAL FIBRES",
    "D01D": "MECHANICAL METHODS OR APPARATUS IN THE MANUFACTURE OF ARTIFICIAL FILAMENTS, THREADS, FIBRES, BRISTLES, OR RIBBONS",
    "D01F": "CHEMICAL FEATURES IN THE MANUFACTURE OF ARTIFICIAL FILAMENTS, THREADS, FIBRES, BRISTLES, OR RIBBONS; APPARATUS SPECIALLY ADAPTED FOR THE MANUFACTURE OF CARBON FILAMENTS",
    "D01G": "PRELIMINARY TREATMENT OF FIBRES, e.g. FOR SPINNING",
    "D01H": "SPINNING OR TWISTING",
    "D02G": "CRIMPING OR CURLING FIBRES, FILAMENTS, YARNS, OR THREADS; YARNS OR THREADS",
    "D02H": "WARPING, BEAMING, OR LEASING",
    "D02J": "FINISHING OR DRESSING OF FILAMENTS, YARNS, THREADS, CORDS, ROPES, OR THE LIKE",
    "D03C": "SHEDDING MECHANISMS; PATTERN CARDS OR CHAINS; PUNCHING OF CARDS; DESIGNING PATTERNS",
    "D03D": "WOVEN FABRICS; METHODS OF WEAVING; LOOMS",
    "D03J": "AUXILIARY WEAVING APPARATUS; WEAVERS' TOOLS; SHUTTLES",
    "D04B": "KNITTING",
    "D04C": "BRAIDING OR MANUFACTURE OF LACE, INCLUDING BOBBIN-NET OR CARBONISED LACE; BRAIDING MACHINES; BRAID; LACE",
    "D04D": "TRIMMINGS; RIBBONS, TAPES, OR BANDS, NOT OTHERWISE PROVIDED FOR",
    "D04G": "MAKING NETS BY KNOTTING OF FILAMENTARY MATERIAL; MAKING KNOTTED CARPETS OR TAPESTRIES; KNOTTING NOT OTHERWISE PROVIDED FOR ;",
    "D04H": "MAKING TEXTILE FABRICS, e.g. FROM FIBRES OR FILAMENTARY MATERIAL",
    "D05B": "SEWING",
    "D05C": "EMBROIDERING",
    "D06B": "TREATING TEXTILE MATERIALS BY LIQUIDS, GASES, OR VAPOURS",
    "D06C": "FINISHING, DRESSING, TENTERING, OR STRETCHING TEXTILE FABRICS",
    "D06F": "LAUNDERING, DRYING, IRONING, PRESSING OR FOLDING TEXTILE ARTICLES",
    "D06G": "MECHANICAL OR PRESSURE CLEANING OF CARPETS, RUGS, SACKS, HIDES, OR OTHER SKIN OR TEXTILE ARTICLES OR FABRICS; TURNING INSIDE-OUT FLEXIBLE TUBULAR OR OTHER HOLLOW ARTICLES",
    "D06H": "MARKING, INSPECTING, SEAMING, OR SEVERING TEXTILE MATERIALS ;",
    "D06J": "PLEATING, KILTING, OR GOFFERING TEXTILE FABRICS OR WEARING APPAREL",
    "D06L": "BLEACHING, e.g. OPTICAL BLEACHING, DRY-CLEANING, OR WASHING FIBRES, THREADS, YARNS, FABRICS, FEATHERS, OR MADE-UP FIBROUS GOODS; BLEACHING LEATHER OR FURS",
    "D06M": "TREATMENT, NOT PROVIDED FOR ELSEWHERE IN CLASS  D06, OF FIBRES, THREADS, YARNS, FABRICS, FEATHERS, OR FIBROUS GOODS MADE FROM SUCH MATERIALS",
    "D06N": "WALL, FLOOR, OR LIKE COVERING MATERIALS, e.g. LINOLEUM, OILCLOTH, ARTIFICIAL LEATHER, ROOFING FELT, CONSISTING OF A FIBROUS WEB COATED WITH A LAYER OF MACROMOLECULAR MATERIAL; FLEXIBLE SHEET MATERIAL NOT OTHERWISE PROVIDED FOR",
    "D06P": "DYEING OR PRINTING TEXTILES; DYEING LEATHER, FURS, OR SOLID MACROMOLECULAR SUBSTANCES IN ANY FORM",
    "D06Q": "DECORATING TEXTILES",
    "D07B": "ROPES OR CABLES IN GENERAL",
    "D21B": "FIBROUS RAW MATERIALS OR THEIR MECHANICAL TREATMENT",
    "D21C": "PRODUCTION OF CELLULOSE BY REMOVING NON-CELLULOSE SUBSTANCES FROM CELLULOSE- CONTAINING MATERIALS; REGENERATION OF PULPING LIQUORS; APPARATUS THEREFOR",
    "D21D": "TREATMENT OF THE MATERIALS BEFORE PASSING TO THE PAPER-MAKING MACHINE",
    "D21F": "PAPER-MAKING MACHINES; METHODS OF PRODUCING PAPER THEREON",
    "D21G": "CALENDERS; ACCESSORIES FOR PAPER-MAKING MACHINES",
    "D21H": "PULP COMPOSITIONS; PREPARATION THEREOF NOT COVERED BY SUBCLASSES ; D21C, D21D; IMPREGNATING OR COATING OF PAPER; TREATMENT OF FINISHED PAPER NOT COVERED BY CLASS ; B31;  OR SUBCLASS D21G; PAPER NOT OTHERWISE PROVIDED FOR",
    "D21J": "FIBREBOARD; MANUFACTURE OF ARTICLES FROM CELLULOSIC FIBROUS SUSPENSIONS OR FROM PAPIER-MÂCHÉ",
    "D99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "E01B": "PERMANENT WAY; PERMANENT-WAY TOOLS; MACHINES FOR MAKING RAILWAYS OF ALL KINDS",
    "E01C": "CONSTRUCTION OF, OR SURFACES FOR, ROADS, SPORTS GROUNDS, OR THE LIKE; MACHINES OR AUXILIARY TOOLS FOR CONSTRUCTION OR REPAIR",
    "E01D": "BRIDGES",
    "E01F": "ADDITIONAL WORK, SUCH AS EQUIPPING ROADS OR THE CONSTRUCTION OF PLATFORMS, HELICOPTER LANDING STAGES, SIGNS, SNOW FENCES, OR THE LIKE",
    "E01H": "STREET CLEANING; CLEANING OF PERMANENT WAYS; CLEANING BEACHES; CLEANING LAND; DISPERSING FOG IN GENERAL",
    "E02B": "HYDRAULIC ENGINEERING",
    "E02C": "SHIP-LIFTING DEVICES OR MECHANISMS",
    "E02D": "FOUNDATIONS; EXCAVATIONS; EMBANKMENTS ; UNDERGROUND OR UNDERWATER STRUCTURES",
    "E02F": "DREDGING; SOIL-SHIFTING",
    "E03B": "INSTALLATIONS OR METHODS FOR OBTAINING, COLLECTING, OR DISTRIBUTING WATER",
    "E03C": "DOMESTIC PLUMBING INSTALLATIONS FOR FRESH WATER OR WASTE WATER ; SINKS",
    "E03D": "WATER-CLOSETS OR URINALS WITH FLUSHING DEVICES; FLUSHING VALVES THEREFOR",
    "E03F": "SEWERS; CESSPOOLS",
    "E04B": "GENERAL BUILDING CONSTRUCTIONS; WALLS, e.g. PARTITIONS; ROOFS; FLOORS; CEILINGS; INSULATION OR OTHER PROTECTION OF BUILDINGS",
    "E04C": "STRUCTURAL ELEMENTS; BUILDING MATERIALS",
    "E04D": "ROOF COVERINGS; SKY-LIGHTS; GUTTERS; ROOF-WORKING TOOLS",
    "E04F": "FINISHING WORK ON BUILDINGS, e.g. STAIRS, FLOORS",
    "E04G": "SCAFFOLDING; FORMS; SHUTTERING; BUILDING IMPLEMENTS OR OTHER BUILDING AIDS, OR THEIR USE; HANDLING BUILDING MATERIALS ON THE SITE; REPAIRING, BREAKING-UP OR OTHER WORK ON EXISTING BUILDINGS",
    "E04H": "BUILDINGS OR LIKE STRUCTURES FOR PARTICULAR PURPOSES; SWIMMING OR SPLASH BATHS OR POOLS; MASTS; FENCING; TENTS OR CANOPIES, IN GENERAL",
    "E05B": "LOCKS; ACCESSORIES THEREFOR; HANDCUFFS",
    "E05C": "BOLTS OR FASTENING DEVICES FOR WINGS, SPECIALLY FOR DOORS OR WINDOWS",
    "E05D": "HINGES OR OTHER SUSPENSION DEVICES FOR DOORS, WINDOWS, OR WINGS",
    "E05F": "DEVICES FOR MOVING WINGS INTO OPEN OR CLOSED POSITION; CHECKS FOR WINGS; WING FITTINGS NOT OTHERWISE PROVIDED FOR, CONCERNED WITH THE FUNCTIONING OF THE WING",
    "E05G": "SAFES OR STRONG-ROOMS FOR VALUABLES; BANK PROTECTION DEVICES; SAFETY TRANSACTION PARTITIONS",
    "E06B": "FIXED OR MOVABLE CLOSURES FOR OPENINGS IN BUILDINGS, VEHICLES, FENCES, OR LIKE ENCLOSURES, IN GENERAL, e.g. DOORS, WINDOWS, BLINDS, GATES",
    "E06C": "LADDERS",
    "E21B": "EARTH OR ROCK DRILLING ; OBTAINING OIL, GAS, WATER, SOLUBLE OR MELTABLE MATERIALS OR A SLURRY OF MINERALS FROM WELLS",
    "E21C": "MINING OR QUARRYING",
    "E21D": "SHAFTS; TUNNELS; GALLERIES; LARGE UNDERGROUND CHAMBERS",
    "E21F": "SAFETY DEVICES, TRANSPORT, FILLING-UP, RESCUE, VENTILATION, OR DRAINAGE IN OR OF MINES OR TUNNELS",
    "E99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "F01B": "MACHINES OR ENGINES, IN GENERAL OR OF POSITIVE-DISPLACEMENT TYPE, e.g. STEAM ENGINES",
    "F01C": "ROTARY-PISTON OR OSCILLATING-PISTON MACHINES OR ENGINES",
    "F01D": "NON-POSITIVE-DISPLACEMENT MACHINES OR ENGINES, e.g. STEAM TURBINES",
    "F01K": "STEAM ENGINE PLANTS; STEAM ACCUMULATORS; ENGINE PLANTS NOT OTHERWISE PROVIDED FOR; ENGINES USING SPECIAL WORKING FLUIDS OR CYCLES",
    "F01L": "CYCLICALLY OPERATING VALVES FOR MACHINES OR ENGINES",
    "F01M": "LUBRICATING OF MACHINES OR ENGINES IN GENERAL; LUBRICATING INTERNAL-COMBUSTION ENGINES; CRANKCASE VENTILATING",
    "F01N": "GAS-FLOW SILENCERS OR EXHAUST APPARATUS FOR MACHINES OR ENGINES IN GENERAL; GAS-FLOW SILENCERS OR EXHAUST APPARATUS FOR INTERNAL-COMBUSTION ENGINES",
    "F01P": "COOLING OF MACHINES OR ENGINES IN GENERAL; COOLING OF INTERNAL-COMBUSTION ENGINES",
    "F02B": "INTERNAL-COMBUSTION PISTON ENGINES; COMBUSTION ENGINES IN GENERAL",
    "F02C": "GAS-TURBINE PLANTS; AIR INTAKES FOR JET-PROPULSION PLANTS; CONTROLLING FUEL SUPPLY IN AIR-BREATHING JET-PROPULSION PLANTS ;",
    "F02D": "CONTROLLING COMBUSTION ENGINES ;",
    "F02F": "CYLINDERS, PISTONS, OR CASINGS FOR COMBUSTION ENGINES; ARRANGEMENTS OF SEALINGS IN COMBUSTION ENGINES",
    "F02G": "HOT-GAS OR COMBUSTION-PRODUCT POSITIVE-DISPLACEMENT ENGINE PLANTS ; USE OF WASTE HEAT OF COMBUSTION ENGINES, NOT OTHERWISE PROVIDED FOR",
    "F02K": "JET-PROPULSION PLANTS",
    "F02M": "SUPPLYING COMBUSTION ENGINES IN GENERAL WITH COMBUSTIBLE MIXTURES OR CONSTITUENTS THEREOF",
    "F02N": "STARTING OF COMBUSTION ENGINES ; STARTING AIDS FOR SUCH ENGINES, NOT OTHERWISE PROVIDED FOR",
    "F02P": "IGNITION, OTHER THAN COMPRESSION IGNITION, FOR INTERNAL-COMBUSTION ENGINES; TESTING OF IGNITION TIMING IN COMPRESSION-IGNITION ENGINES",
    "F03B": "MACHINES OR ENGINES FOR LIQUIDS",
    "F03C": "POSITIVE-DISPLACEMENT ENGINES DRIVEN BY LIQUIDS",
    "F03D": "WIND MOTORS",
    "F03G": "SPRING, WEIGHT, INERTIA, OR LIKE MOTORS; MECHANICAL-POWER-PRODUCING DEVICES OR MECHANISMS, NOT OTHERWISE PROVIDED FOR OR USING ENERGY SOURCES NOT OTHERWISE PROVIDED FOR",
    "F03H": "PRODUCING A REACTIVE PROPULSIVE THRUST, NOT OTHERWISE PROVIDED FOR",
    "F04B": "POSITIVE-DISPLACEMENT MACHINES FOR LIQUIDS; PUMPS",
    "F04C": "ROTARY-PISTON, OR OSCILLATING-PISTON, POSITIVE-DISPLACEMENT MACHINES FOR LIQUIDS",
    "F04D": "NON-POSITIVE-DISPLACEMENT PUMPS",
    "F04F": "PUMPING OF FLUID BY DIRECT CONTACT OF ANOTHER FLUID OR BY USING INERTIA OF FLUID TO BE PUMPED ; SIPHONS",
    "F15B": "SYSTEMS ACTING BY MEANS OF FLUIDS IN GENERAL; FLUID-PRESSURE ACTUATORS, e.g. SERVOMOTORS; DETAILS OF FLUID-PRESSURE SYSTEMS, NOT OTHERWISE PROVIDED FOR",
    "F15C": "FLUID-CIRCUIT ELEMENTS PREDOMINANTLY USED FOR COMPUTING OR CONTROL PURPOSES",
    "F15D": "FLUID DYNAMICS, i.e. METHODS OR MEANS FOR INFLUENCING THE FLOW OF GASES OR LIQUIDS",
    "F16B": "DEVICES FOR FASTENING OR SECURING CONSTRUCTIONAL ELEMENTS OR MACHINE PARTS TOGETHER, e.g. NAILS, BOLTS, CIRCLIPS, CLAMPS, CLIPS OR WEDGES; JOINTS OR JOINTING",
    "F16C": "SHAFTS; FLEXIBLE SHAFTS; MECHANICAL MEANS FOR TRANSMITTING MOVEMENT IN A FLEXIBLE SHEATHING; ELEMENTS OF CRANKSHAFT MECHANISMS; PIVOTS; PIVOTAL CONNECTIONS; ROTARY ENGINEERING ELEMENTS OTHER THAN GEARING, COUPLING, CLUTCH OR BRAKE ELEMENTS; BEARINGS",
    "F16D": "COUPLINGS FOR TRANSMITTING ROTATION",
    "F16F": "SPRINGS; SHOCK-ABSORBERS; MEANS FOR DAMPING VIBRATION",
    "F16G": "BELTS, CABLES, OR ROPES, PREDOMINANTLY USED FOR DRIVING PURPOSES; CHAINS; FITTINGS PREDOMINANTLY USED THEREFOR",
    "F16H": "GEARING",
    "F16J": "PISTONS; CYLINDERS; PRESSURE VESSELS IN GENERAL; SEALINGS",
    "F16K": "VALVES; TAPS; COCKS; ACTUATING-FLOATS; DEVICES FOR VENTING OR AERATING",
    "F16L": "PIPES; JOINTS OR FITTINGS FOR PIPES; SUPPORTS FOR PIPES, CABLES OR PROTECTIVE TUBING; MEANS FOR THERMAL INSULATION IN GENERAL",
    "F16M": "FRAMES, CASINGS, OR BEDS, OF ENGINES OR OTHER MACHINES OR APPARATUS, NOT SPECIFIC TO AN ENGINE, MACHINE, OR APPARATUS PROVIDED FOR ELSEWHERE; STANDS OR SUPPORTS",
    "F16N": "LUBRICATING",
    "F16P": "SAFETY DEVICES IN GENERAL",
    "F16S": "CONSTRUCTIONAL ELEMENTS IN GENERAL; STRUCTURES BUILT-UP FROM SUCH ELEMENTS, IN GENERAL",
    "F16T": "STEAM TRAPS OR LIKE APPARATUS FOR DRAINING-OFF LIQUIDS FROM ENCLOSURES PREDOMINANTLY CONTAINING GASES OR VAPOURS",
    "F17B": "GAS-HOLDERS OF VARIABLE CAPACITY",
    "F17C": "VESSELS FOR CONTAINING OR STORING COMPRESSED, LIQUEFIED, OR SOLIDIFIED GASES; FIXED-CAPACITY GAS-HOLDERS; FILLING VESSELS WITH, OR DISCHARGING FROM VESSELS, COMPRESSED, LIQUEFIED, OR SOLIDIFIED GASES",
    "F17D": "PIPE-LINE SYSTEMS; PIPE-LINES",
    "F21H": "INCANDESCENT MANTLES; OTHER INCANDESCENT BODIES HEATED BY COMBUSTION",
    "F21K": "LIGHT SOURCES NOT OTHERWISE PROVIDED FOR",
    "F21L": "LIGHTING DEVICES OR SYSTEMS THEREOF, BEING PORTABLE OR SPECIALLY ADAPTED FOR TRANSPORTATION",
    "F21S": "NON-PORTABLE LIGHTING DEVICES OR SYSTEMS THEREOF",
    "F21V": "FUNCTIONAL FEATURES OR DETAILS OF LIGHTING DEVICES OR SYSTEMS THEREOF; STRUCTURAL COMBINATIONS OF LIGHTING DEVICES WITH OTHER ARTICLES, NOT OTHERWISE PROVIDED FOR",
    "F21W": "INDEXING SCHEME ASSOCIATED WITH SUBCLASSES F21L, F21S and F21V, RELATING TO USES OR APPLICATIONS OF LIGHTING DEVICES OR SYSTEMS",
    "F21Y": "INDEXING SCHEME ASSOCIATED WITH SUBCLASSES F21L, F21S and F21V, RELATING TO THE FORM OF THE LIGHT SOURCES",
    "F22B": "METHODS OF STEAM GENERATION; STEAM BOILERS",
    "F22D": "PREHEATING, OR ACCUMULATING PREHEATED, FEED-WATER; FEED-WATER SUPPLY; CONTROLLING WATER LEVEL;  AUXILIARY DEVICES FOR PROMOTING WATER CIRCULATION WITHIN BOILERS",
    "F22G": "SUPERHEATING OF STEAM",
    "F23B": "METHODS OR APPARATUS FOR COMBUSTION USING ONLY SOLID FUEL",
    "F23C": "METHODS OR APPARATUS FOR COMBUSTION USING FLUID FUEL OR SOLID FUEL SUSPENDED IN AIR",
    "F23D": "BURNERS",
    "F23G": "CREMATION FURNACES; CONSUMING WASTE OR LOW GRADE FUELS BY COMBUSTION",
    "F23H": "GRATES ; CLEANING OR RAKING GRATES",
    "F23J": "REMOVAL OR TREATMENT OF COMBUSTION PRODUCTS OR COMBUSTION RESIDUES; FLUES",
    "F23K": "FEEDING FUEL TO COMBUSTION APPARATUS",
    "F23L": "SUPPLYING AIR OR NON-COMBUSTIBLE LIQUIDS OR GASES TO COMBUSTION APPARATUS IN GENERAL; VALVES OR DAMPERS SPECIALLY ADAPTED FOR CONTROLLING AIR SUPPLY OR DRAUGHT IN COMBUSTION APPARATUS; INDUCING DRAUGHT IN COMBUSTION APPARATUS; TOPS FOR CHIMNEYS OR VENTILATING SHAFTS; TERMINALS FOR FLUES",
    "F23M": "CONSTRUCTIONAL DETAILS OF COMBUSTION CHAMBERS, NOT OTHERWISE PROVIDED FOR",
    "F23N": "REGULATING OR CONTROLLING COMBUSTION",
    "F23Q": "IGNITION ; EXTINGUISHING DEVICES",
    "F23R": "GENERATING COMBUSTION PRODUCTS OF HIGH PRESSURE OR HIGH VELOCITY, e.g. GAS-TURBINE COMBUSTION CHAMBERS",
    "F24B": "DOMESTIC STOVES OR RANGES FOR SOLID FUELS; IMPLEMENTS FOR USE IN CONNECTION WITH STOVES OR RANGES",
    "F24C": "OTHER DOMESTIC STOVES OR RANGES; DETAILS OF DOMESTIC STOVES OR RANGES, OF GENERAL APPLICATION",
    "F24D": "DOMESTIC- OR SPACE-HEATING SYSTEMS, e.g. CENTRAL HEATING SYSTEMS; DOMESTIC HOT-WATER SUPPLY SYSTEMS; ELEMENTS OR COMPONENTS THEREFOR",
    "F24F": "AIR-CONDITIONING; AIR-HUMIDIFICATION; VENTILATION; USE OF AIR CURRENTS FOR SCREENING",
    "F24H": "FLUID HEATERS, e.g. WATER OR AIR HEATERS, HAVING HEAT-GENERATING MEANS, IN GENERAL",
    "F24J": "PRODUCTION OR USE OF HEAT NOT OTHERWISE PROVIDED FOR ;",
    "F25B": "REFRIGERATION MACHINES, PLANTS, OR SYSTEMS; COMBINED HEATING AND REFRIGERATION SYSTEMS; HEAT PUMP SYSTEMS",
    "F25C": "PRODUCTION, WORKING, STORING OR DISTRIBUTION OF ICE",
    "F25D": "REFRIGERATORS; COLD ROOMS; ICE-BOXES; COOLING OR FREEZING APPARATUS NOT COVERED BY ANY OTHER SUBCLASS ;",
    "F25J": "LIQUEFACTION, SOLIDIFICATION, OR SEPARATION OF GASES OR GASEOUS MIXTURES BY PRESSURE AND COLD TREATMENT",
    "F26B": "DRYING SOLID MATERIALS OR OBJECTS BY REMOVING LIQUID THEREFROM",
    "F27B": "FURNACES, KILNS, OVENS, OR RETORTS IN GENERAL; OPEN SINTERING OR LIKE APPARATUS",
    "F27D": "DETAILS OR ACCESSORIES OF FURNACES, KILNS, OVENS, OR RETORTS, IN SO FAR AS THEY ARE OF KINDS OCCURRING IN MORE THAN ONE KIND OF FURNACE",
    "F28B": "STEAM OR VAPOUR CONDENSERS",
    "F28C": "HEAT-EXCHANGE APPARATUS, NOT PROVIDED FOR IN ANOTHER SUBCLASS, IN WHICH THE HEAT-EXCHANGE MEDIA COME INTO DIRECT CONTACT WITHOUT CHEMICAL INTERACTION",
    "F28D": "HEAT-EXCHANGE APPARATUS, NOT PROVIDED FOR IN ANOTHER SUBCLASS, IN WHICH THE HEAT-EXCHANGE MEDIA DO NOT COME INTO DIRECT CONTACT ; HEAT STORAGE PLANTS OR APPARATUS IN GENERAL",
    "F28F": "DETAILS OF HEAT-EXCHANGE OR HEAT-TRANSFER APPARATUS, OF GENERAL APPLICATION",
    "F28G": "CLEANING OF INTERNAL OR EXTERNAL SURFACES OF HEAT-EXCHANGE OR HEAT-TRANSFER CONDUITS, e.g. WATER TUBES OF BOILERS",
    "F41A": "FUNCTIONAL FEATURES OR DETAILS COMMON TO BOTH SMALLARMS AND ORDNANCE, e.g. CANNONS; MOUNTINGS FOR SMALLARMS OR ORDNANCE",
    "F41B": "WEAPONS FOR PROJECTING MISSILES WITHOUT USE OF EXPLOSIVE OR COMBUSTIBLE PROPELLANT CHARGE; WEAPONS NOT OTHERWISE PROVIDED FOR",
    "F41C": "SMALLARMS, e.g. PISTOLS OR RIFLES ; ACCESSORIES THEREFOR",
    "F41F": "APPARATUS FOR LAUNCHING PROJECTILES OR MISSILES FROM BARRELS, e.g. CANNONS",
    "F41G": "WEAPON SIGHTS; AIMING",
    "F41H": "ARMOUR; ARMOURED TURRETS; ARMOURED OR ARMED VEHICLES; MEANS OF ATTACK OR DEFENCE, e.g. CAMOUFLAGE, IN GENERAL",
    "F41J": "TARGETS; TARGET RANGES; BULLET CATCHERS",
    "F42B": "EXPLOSIVE CHARGES, e.g. FOR BLASTING; FIREWORKS; AMMUNITION",
    "F42C": "AMMUNITION FUZES",
    "F42D": "BLASTING",
    "F99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "G01B": "MEASURING LENGTH, THICKNESS OR SIMILAR LINEAR DIMENSIONS; MEASURING ANGLES; MEASURING AREAS; MEASURING IRREGULARITIES OF SURFACES OR CONTOURS",
    "G01C": "MEASURING DISTANCES, LEVELS OR BEARINGS; SURVEYING; NAVIGATION; GYROSCOPIC INSTRUMENTS; PHOTOGRAMMETRY OR VIDEOGRAMMETRY",
    "G01D": "MEASURING NOT SPECIALLY ADAPTED FOR A SPECIFIC VARIABLE; ARRANGEMENTS FOR MEASURING TWO OR MORE VARIABLES NOT COVERED BY A SINGLE OTHER SUBCLASS; TARIFF METERING APPARATUS; TRANSFERRING OR TRANSDUCING ARRANGEMENTS NOT SPECIALLY ADAPTED FOR A SPECIFIC VARIABLE; MEASURING OR TESTING NOT OTHERWISE PROVIDED FOR",
    "G01F": "MEASURING VOLUME, VOLUME FLOW, MASS FLOW, OR LIQUID LEVEL; METERING BY VOLUME",
    "G01G": "WEIGHING",
    "G01H": "MEASUREMENT OF MECHANICAL VIBRATIONS OR ULTRASONIC, SONIC OR INFRASONIC WAVES",
    "G01J": "MEASUREMENT OF INTENSITY, VELOCITY, SPECTRAL CONTENT, POLARISATION, PHASE OR PULSE CHARACTERISTICS OF INFRA-RED, VISIBLE OR ULTRA-VIOLET LIGHT; COLORIMETRY; RADIATION PYROMETRY",
    "G01K": "MEASURING TEMPERATURE; MEASURING QUANTITY OF HEAT; THERMALLY-SENSITIVE ELEMENTS NOT OTHERWISE PROVIDED FOR",
    "G01L": "MEASURING FORCE, STRESS, TORQUE, WORK, MECHANICAL POWER, MECHANICAL EFFICIENCY, OR FLUID PRESSURE",
    "G01M": "TESTING STATIC OR DYNAMIC BALANCE OF MACHINES OR STRUCTURES; TESTING OF STRUCTURES OR APPARATUS, NOT OTHERWISE PROVIDED FOR",
    "G01N": "INVESTIGATING OR ANALYSING MATERIALS BY DETERMINING THEIR CHEMICAL OR PHYSICAL PROPERTIES",
    "G01P": "MEASURING LINEAR OR ANGULAR SPEED, ACCELERATION, DECELERATION OR SHOCK; INDICATING PRESENCE OR ABSENCE OF MOVEMENT;  INDICATING DIRECTION OF MOVEMENT ",
    "G01Q": "SCANNING-PROBE TECHNIQUES OR APPARATUS; APPLICATIONS OF SCANNING-PROBE TECHNIQUES, e.g. SCANNING-PROBE MICROSCOPY [SPM]",
    "G01R": "MEASURING ELECTRIC VARIABLES; MEASURING MAGNETIC VARIABLES",
    "G01S": "RADIO DIRECTION-FINDING; RADIO NAVIGATION; DETERMINING DISTANCE OR VELOCITY BY USE OF RADIO WAVES; LOCATING OR PRESENCE-DETECTING BY USE OF THE REFLECTION OR RERADIATION OF RADIO WAVES; ANALOGOUS ARRANGEMENTS USING OTHER WAVES",
    "G01T": "MEASUREMENT OF NUCLEAR OR X-RADIATION",
    "G01V": "GEOPHYSICS; GRAVITATIONAL MEASUREMENTS; DETECTING MASSES OR OBJECTS; TAGS",
    "G01W": "METEOROLOGY",
    "G02B": "OPTICAL ELEMENTS, SYSTEMS, OR APPARATUS",
    "G02C": "SPECTACLES; SUNGLASSES OR GOGGLES INSOFAR AS THEY HAVE THE SAME FEATURES AS SPECTACLES; CONTACT LENSES",
    "G02F": "DEVICES OR ARRANGEMENTS, THE OPTICAL OPERATION OF WHICH IS MODIFIED BY CHANGING THE OPTICAL PROPERTIES OF THE MEDIUM OF THE DEVICES OR ARRANGEMENTS FOR THE CONTROL OF THE INTENSITY, COLOUR, PHASE, POLARISATION OR DIRECTION OF LIGHT, e.g. SWITCHING, GATING, MODULATING OR DEMODULATING; TECHNIQUES OR PROCEDURES FOR THE OPERATION THEREOF; FREQUENCY-CHANGING; NON-LINEAR OPTICS; OPTICAL LOGIC ELEMENTS; OPTICAL ANALOGUE/DIGITAL CONVERTERS",
    "G03B": "APPARATUS OR ARRANGEMENTS FOR TAKING PHOTOGRAPHS OR FOR PROJECTING OR VIEWING THEM; APPARATUS OR ARRANGEMENTS EMPLOYING ANALOGOUS TECHNIQUES USING WAVES OTHER THAN OPTICAL WAVES; ACCESSORIES THEREFOR",
    "G03C": "PHOTOSENSITIVE MATERIALS FOR PHOTOGRAPHIC PURPOSES; PHOTOGRAPHIC PROCESSES, e.g. CINE, X-RAY, COLOUR OR STEREO-PHOTOGRAPHIC PROCESSES; AUXILIARY PROCESSES IN PHOTOGRAPHY",
    "G03D": "APPARATUS FOR PROCESSING EXPOSED PHOTOGRAPHIC MATERIALS; ACCESSORIES THEREFOR",
    "G03F": "PHOTOMECHANICAL PRODUCTION OF TEXTURED OR PATTERNED SURFACES, e.g. FOR PRINTING, FOR PROCESSING OF SEMICONDUCTOR DEVICES; MATERIALS THEREFOR; ORIGINALS THEREFOR; APPARATUS SPECIALLY ADAPTED THEREFOR",
    "G03G": "ELECTROGRAPHY; ELECTROPHOTOGRAPHY; MAGNETOGRAPHY",
    "G03H": "HOLOGRAPHIC PROCESSES OR APPARATUS",
    "G04B": "MECHANICALLY-DRIVEN CLOCKS OR WATCHES; MECHANICAL PARTS OF CLOCKS OR WATCHES IN GENERAL; TIME-PIECES USING THE POSITION OF THE SUN, MOON, OR STARS",
    "G04C": "ELECTROMECHANICAL CLOCKS OR WATCHES",
    "G04D": "APPARATUS OR TOOLS SPECIALLY DESIGNED FOR MAKING OR MAINTAINING CLOCKS OR WATCHES",
    "G04F": "TIME-INTERVAL MEASURING",
    "G04G": "ELECTRONIC TIME-PIECES",
    "G04R": "RADIO-CONTROLLED TIME-PIECES",
    "G05B": "CONTROL OR REGULATING SYSTEMS IN GENERAL; FUNCTIONAL ELEMENTS OF SUCH SYSTEMS; MONITORING OR TESTING ARRANGEMENTS FOR SUCH SYSTEMS OR ELEMENTS",
    "G05D": "SYSTEMS FOR CONTROLLING OR REGULATING NON-ELECTRIC VARIABLES",
    "G05F": "SYSTEMS FOR REGULATING ELECTRIC OR MAGNETIC VARIABLES",
    "G05G": "CONTROL DEVICES OR SYSTEMS INSOFAR AS CHARACTERISED BY MECHANICAL FEATURES ONLY",
    "G06C": "DIGITAL COMPUTERS IN WHICH ALL THE COMPUTATION IS EFFECTED MECHANICALLY",
    "G06D": "DIGITAL FLUID-PRESSURE COMPUTING DEVICES",
    "G06E": "OPTICAL COMPUTING DEVICES",
    "G06F": "ELECTRIC DIGITAL DATA PROCESSING",
    "G06G": "ANALOGUE COMPUTERS",
    "G06J": "HYBRID COMPUTING ARRANGEMENTS",
    "G06K": "RECOGNITION OF DATA; PRESENTATION OF DATA; RECORD CARRIERS; HANDLING RECORD CARRIERS",
    "G06M": "COUNTING MECHANISMS; COUNTING OF OBJECTS NOT OTHERWISE PROVIDED FOR",
    "G06N": "COMPUTER SYSTEMS BASED ON SPECIFIC COMPUTATIONAL MODELS",
    "G06Q": "DATA PROCESSING SYSTEMS OR METHODS, SPECIALLY ADAPTED FOR ADMINISTRATIVE, COMMERCIAL, FINANCIAL, MANAGERIAL, SUPERVISORY OR FORECASTING PURPOSES; SYSTEMS OR METHODS SPECIALLY ADAPTED FOR ADMINISTRATIVE, COMMERCIAL, FINANCIAL, MANAGERIAL, SUPERVISORY OR FORECASTING PURPOSES, NOT OTHERWISE PROVIDED FOR",
    "G06T": "IMAGE DATA PROCESSING OR GENERATION, IN GENERAL",
    "G07B": "TICKET-ISSUING APPARATUS; TAXIMETERS; ARRANGEMENTS OR APPARATUS FOR COLLECTING FARES, TOLLS OR ENTRANCE FEES AT ONE OR MORE CONTROL POINTS;  FRANKING APPARATUS",
    "G07C": "TIME OR ATTENDANCE REGISTERS; REGISTERING OR INDICATING THE WORKING OF MACHINES; GENERATING RANDOM NUMBERS; VOTING OR LOTTERY APPARATUS; ARRANGEMENTS, SYSTEMS, OR APPARATUS FOR CHECKING NOT PROVIDED FOR ELSEWHERE",
    "G07D": "HANDLING OF COINS OR OF PAPER CURRENCY OR SIMILAR VALUABLE PAPERS, e.g. TESTING, SORTING BY DENOMINATIONS, COUNTING, DISPENSING, CHANGING OR DEPOSITING",
    "G07F": "COIN-FREED OR LIKE APPARATUS",
    "G07G": "REGISTERING THE RECEIPT OF CASH, VALUABLES, OR TOKENS",
    "G08B": "SIGNALLING OR CALLING SYSTEMS; ORDER TELEGRAPHS; ALARM SYSTEMS",
    "G08C": "TRANSMISSION SYSTEMS FOR MEASURED VALUES, CONTROL OR SIMILAR SIGNALS",
    "G08G": "TRAFFIC CONTROL SYSTEMS",
    "G09B": "EDUCATIONAL OR DEMONSTRATION APPLIANCES; APPLIANCES FOR TEACHING, OR COMMUNICATING WITH, THE BLIND, DEAF OR MUTE; MODELS; PLANETARIA; GLOBES; MAPS; DIAGRAMS",
    "G09C": "CIPHERING OR DECIPHERING APPARATUS FOR CRYPTOGRAPHIC OR OTHER PURPOSES INVOLVING THE NEED FOR SECRECY",
    "G09D": "RAILWAY OR LIKE TIME OR FARE TABLES; PERPETUAL CALENDARS",
    "G09F": "DISPLAYING; ADVERTISING; SIGNS; LABELS OR NAME-PLATES; SEALS",
    "G09G": "ARRANGEMENTS OR CIRCUITS FOR CONTROL OF INDICATING DEVICES USING STATIC MEANS TO PRESENT VARIABLE INFORMATION",
    "G10B": "ORGANS, HARMONIUMS OR LIKE WIND-ACTUATED MUSICAL INSTRUMENTS",
    "G10C": "PIANOS, HARPSICHORDS, SPINETS OR SIMILAR STRINGED MUSICAL INSTRUMENTS WITH ONE OR MORE KEYBOARDS",
    "G10D": "STRINGED MUSICAL INSTRUMENTS; WIND-ACTUATED MUSICAL INSTRUMENTS; ACCORDIONS OR CONCERTINAS; PERCUSSION MUSICAL INSTRUMENTS; MUSICAL INSTRUMENTS NOT OTHERWISE PROVIDED FO",
    "G10F": "AUTOMATIC MUSICAL INSTRUMENTS",
    "G10G": "AIDS FOR MUSIC; SUPPORTS FOR MUSICAL INSTRUMENTS; OTHER AUXILIARY DEVICES OR ACCESSORIES FOR MUSIC OR MUSICAL INSTRUMENTS",
    "G10H": "ELECTROPHONIC MUSICAL INSTRUMENTS; INSTRUMENTS IN WHICH THE TONES ARE GENERATED BY ELECTROMECHANICAL MEANS OR ELECTRONIC GENERATORS, OR IN WHICH THE TONES ARE SYNTHESISED FROM A DATA STORE",
    "G10K": "SOUND-PRODUCING DEVICES ;  METHODS OR DEVICES FOR PROTECTING AGAINST, OR FOR DAMPING, NOISE OR OTHER ACOUSTIC WAVES IN GENERAL; ACOUSTICS NOT OTHERWISE PROVIDED FOR",
    "G10L": "SPEECH ANALYSIS OR SYNTHESIS; SPEECH RECOGNITION; SPEECH OR VOICE PROCESSING; SPEECH OR AUDIO CODING OR DECODING",
    "G11B": "INFORMATION STORAGE BASED ON RELATIVE MOVEMENT BETWEEN RECORD CARRIER AND TRANSDUCER",
    "G11C": "STATIC STORES",
    "G12B": "CONSTRUCTIONAL DETAILS OF INSTRUMENTS, OR COMPARABLE DETAILS OF OTHER APPARATUS, NOT OTHERWISE PROVIDED FOR",
    "G21B": "FUSION REACTORS",
    "G21C": "NUCLEAR REACTORS",
    "G21D": "NUCLEAR POWER PLANT",
    "G21F": "PROTECTION AGAINST X-RADIATION, GAMMA RADIATION, CORPUSCULAR RADIATION OR PARTICLE BOMBARDMENT; TREATING RADIOACTIVELY CONTAMINATED MATERIAL; DECONTAMINATION ARRANGEMENTS THEREFOR",
    "G21G": "CONVERSION OF CHEMICAL ELEMENTS; RADIOACTIVE SOURCES",
    "G21H": "OBTAINING ENERGY FROM RADIOACTIVE SOURCES; APPLICATIONS OF RADIATION FROM RADIOACTIVE SOURCES; UTILISING COSMIC RADIATION",
    "G21J": "NUCLEAR EXPLOSIVES; APPLICATIONS THEREOF",
    "G21K": "TECHNIQUES FOR HANDLING PARTICLES OR IONISING RADIATION NOT OTHERWISE PROVIDED FOR; IRRADIATION DEVICES; GAMMA RAY OR X-RAY MICROSCOPES",
    "G99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION",
    "H01B": "CABLES; CONDUCTORS; INSULATORS; SELECTION OF MATERIALS FOR THEIR CONDUCTIVE, INSULATING OR DIELECTRIC PROPERTIES",
    "H01C": "RESISTORS",
    "H01F": "MAGNETS; INDUCTANCES; TRANSFORMERS; SELECTION OF MATERIALS FOR THEIR MAGNETIC PROPERTIES",
    "H01G": "CAPACITORS; CAPACITORS, RECTIFIERS, DETECTORS, SWITCHING DEVICES, LIGHT-SENSITIVE OR TEMPERATURE-SENSITIVE DEVICES OF THE ELECTROLYTIC TYPE",
    "H01H": "ELECTRIC SWITCHES; RELAYS; SELECTORS; EMERGENCY PROTECTIVE DEVICES",
    "H01J": "ELECTRIC DISCHARGE TUBES OR DISCHARGE LAMPS",
    "H01K": "ELECTRIC INCANDESCENT LAMPS",
    "H01L": "SEMICONDUCTOR DEVICES; ELECTRIC SOLID STATE DEVICES NOT OTHERWISE PROVIDED FOR ;",
    "H01M": "PROCESSES OR MEANS, e.g. BATTERIES, FOR THE DIRECT CONVERSION OF CHEMICAL ENERGY INTO ELECTRICAL ENERGY",
    "H01P": "WAVEGUIDES; RESONATORS, LINES OR OTHER DEVICES OF THE WAVEGUIDE TYPE",
    "H01Q": "AERIALS",
    "H01R": "ELECTRICALLY-CONDUCTIVE CONNECTIONS; STRUCTURAL ASSOCIATIONS OF A PLURALITY OF MUTUALLY-INSULATED ELECTRICAL CONNECTING ELEMENTS; COUPLING DEVICES; CURRENT COLLECTORS",
    "H01S": "DEVICES USING STIMULATED EMISSION",
    "H01T": "SPARK GAPS; OVERVOLTAGE ARRESTERS USING SPARK GAPS; SPARKING PLUGS; CORONA DEVICES; GENERATING IONS TO BE INTRODUCED INTO NON-ENCLOSED GASES",
    "H02B": "BOARDS, SUBSTATIONS, OR SWITCHING ARRANGEMENTS FOR THE SUPPLY OR DISTRIBUTION OF ELECTRIC POWER",
    "H02G": "INSTALLATION OF ELECTRIC CABLES OR LINES, OR OF COMBINED OPTICAL AND ELECTRIC CABLES OR LINES",
    "H02H": "EMERGENCY PROTECTIVE CIRCUIT ARRANGEMENTS",
    "H02J": "CIRCUIT ARRANGEMENTS OR SYSTEMS FOR SUPPLYING OR DISTRIBUTING ELECTRIC POWER; SYSTEMS FOR STORING ELECTRIC ENERGY",
    "H02K": "DYNAMO-ELECTRIC MACHINES",
    "H02M": "APPARATUS FOR CONVERSION BETWEEN AC AND AC, BETWEEN AC AND DC, OR BETWEEN DC AND DC, AND FOR USE WITH MAINS OR SIMILAR POWER SUPPLY SYSTEMS; CONVERSION OF DC OR AC INPUT POWER INTO SURGE OUTPUT POWER; CONTROL OR REGULATION THEREOF",
    "H02N": "ELECTRIC MACHINES NOT OTHERWISE PROVIDED FOR",
    "H02P": "CONTROL OR REGULATION OF ELECTRIC MOTORS, GENERATORS, OR DYNAMO-ELECTRIC CONVERTERS; CONTROLLING TRANSFORMERS OR REACTORS OR CHOKE COILS",
    "H03B": "GENERATION OF OSCILLATIONS, DIRECTLY OR BY FREQUENCY-CHANGING, BY CIRCUITS EMPLOYING ACTIVE ELEMENTS WHICH OPERATE IN A NON-SWITCHING MANNER; GENERATION OF NOISE BY SUCH CIRCUITS",
    "H03C": "MODULATION",
    "H03D": "DEMODULATION OR TRANSFERENCE OF MODULATION FROM ONE CARRIER TO ANOTHER",
    "H03F": "AMPLIFIERS",
    "H03G": "CONTROL OF AMPLIFICATION",
    "H03H": "IMPEDANCE NETWORKS, e.g. RESONANT CIRCUITS; RESONATORS",
    "H03J": "TUNING RESONANT CIRCUITS; SELECTING RESONANT CIRCUITS",
    "H03K": "PULSE TECHNIQUE",
    "H03L": "AUTOMATIC CONTROL, STARTING, SYNCHRONISATION, OR STABILISATION OF GENERATORS OF ELECTRONIC OSCILLATIONS OR PULSES",
    "H03M": "CODING, DECODING OR CODE CONVERSION, IN GENERAL",
    "H04B": "TRANSMISSION",
    "H04H": "BROADCAST COMMUNICATION",
    "H04J": "MULTIPLEX COMMUNICATION",
    "H04K": "SECRET COMMUNICATION; JAMMING OF COMMUNICATION",
    "H04L": "TRANSMISSION OF DIGITAL INFORMATION, e.g. TELEGRAPHIC COMMUNICATION",
    "H04M": "TELEPHONIC COMMUNICATION",
    "H04N": "PICTORIAL COMMUNICATION, e.g. TELEVISION",
    "H04Q": "SELECTING",
    "H04R": "LOUDSPEAKERS, MICROPHONES, GRAMOPHONE PICK-UPS OR LIKE ACOUSTIC ELECTROMECHANICAL TRANSDUCERS; DEAF-AID SETS; PUBLIC ADDRESS SYSTEMS",
    "H04S": "STEREOPHONIC SYSTEMS",
    "H04W": "WIRELESS COMMUNICATION NETWORKS",
    "H05B": "ELECTRIC HEATING; ELECTRIC LIGHTING NOT OTHERWISE PROVIDED FOR",
    "H05C": "ELECTRIC CIRCUITS OR APPARATUS SPECIALLY DESIGNED FOR USE IN EQUIPMENT FOR KILLING, STUNNING, ENCLOSING OR GUIDING LIVING BEINGS",
    "H05F": "STATIC ELECTRICITY; NATURALLY-OCCURRING ELECTRICITY",
    "H05G": "X-RAY TECHNIQUE",
    "H05H": "PLASMA TECHNIQUE",
    "H05K": "PRINTED CIRCUITS; CASINGS OR CONSTRUCTIONAL DETAILS OF ELECTRIC APPARATUS; MANUFACTURE OF ASSEMBLAGES OF ELECTRICAL COMPONENTS ;",
    "H99Z": "SUBJECT MATTER NOT OTHERWISE PROVIDED FOR IN THIS SECTION"
  };

  // export
  var eqip   = this.eqip || {};
  eqip.model = eqip.model || {};
  var ns = eqip.model.static = eqip.model.static || {};
  ns.terrToTGroup = terrToTGroup;
  ns.terrToName = terrToName;
  ns.ipcToName = ipcToName;

})();
